### ISSUE TITLE
Improve error handling on login

### ISSUE THREAD

**Issue by Timothy-D** [exeGesIS-SDM/CAMS-Mobile#10]
From @richardcesdm:
Currently the errors presented when a user fails to login are not very helpful. e.g. if the user gets their password wrong the error returned is: "Cannot connect to the API"

This is both misleading (as it can connect to the API, it just can't authenticate) and unhelpful (as it does not indicate what the user should do to resolve this problem)

**Comment by Timothy-D** [comment]
Noticed in 4.4.6 that when there is no corresponding officer in the vieWebOfficerUsers view it now just gives the message "undefined"; previously it used to say"no officer found" - this seems a retrograde step.

**Comment by Timothy-D** [comment]
Having spent hours wrestling with login problems on various devices & datasets and also checking through Fiddler, I think we need more here:
- There are 2 stages, the login and the officer identification. typically I think the login messages seem to be OK currently (see above)
- On the officer identification, this seems to just report "undefined" for any error, which I'd like to see more diagnostic:
- If the user is not associated with an officer, an empty 200 response is returned. In this case we need to return a message like "No officer found for this login"
- The URL should be valid (as we've just logged in), but I have hit other errors such as 401 unauthorised. In these cases we need to report the error code and description

**Comment by LaineS** [comment]
Invalid user details should be fixed

1. Setup a user in CAMS but make sure they are NOT an officer
2. Login via the app, login proceeds ok but the user details are not found
3. The app should report "Failed to get officer details."
4. The app should then return to the login screen

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 3
**OS Version**: Android 10
**App Version**: 4.5.1
**Sync Account**: xgdev
**Status**: Fail
**Details**:

| Issue | Expectation | Observed Message | Result |
| --- | --- | --- | --- |
| No network connection | Message that there is no internet connection | "No network connection" | OK |
| Invalid API URL | Message that the API could not be reached | "undefined"| NG 🐞 |
| API Offline | Message that the API could not be reached | "undefined"| NG 🐞 |
| Invalid username | Message that user name and/or password are incorrect | "undefined" | NG 🐞 |
| Invalid password | Message that user name and/or password are incorrect | "undefined" | NG 🐞 |
| No officer for that user | Message that the account is not associated with an officer and cannot log in | "Failed to get officer details." | OK |

**Comment by Timothy-D** [comment]
I have also received empty messages if I try to sync with an invalid login (eg logged in on default setup, then changed to a different config and tried to sync; the user form teh defualt is invalid in the current). I think this might be related so including here:
![badMessage](https://user-images.githubusercontent.com/25226464/133757367-78e683c8-9e14-456f-b12e-5ad1cabbd115.png)

**Comment by LaineS** [comment]
v4.5.2

This should be fixed now, there was an issue stopping all messages coming through. Tested by entering an incorrect pwd.

**Comment by Timothy-D** [comment]
**Device**: Emulator
**OS Version**: Android 8.1
**App Version**: 4.5.2
**Sync Account**: xgdev
**Status**: Pass with question
**Details**:

| Issue | Expectation | Observed Message | Result |
| --- | --- | --- | --- |
| Invalid API URL | Message that the API could not be reached | "Status 0: failed to connect to the API"| OK |
| API Offline | Message that the API could not be reached | "Status 404: failed to connect to the API"| OK |
| Invalid username | Message that user name and/or password are incorrect | "Login failed. please check your username and password and API configuration" | OK |
| Invalid password | Message that user name and/or password are incorrect | "Login failed. please check your username and password and API configuration" | OK |
| No officer for that user | Message that the account is not associated with an officer and cannot log in | "Failed to get officer details." | OK |

further testing needed on device, but looks OK

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 3
**OS Version**: Android 11
**App Version**: 4.5.3
**Sync Account**: xgDev
**Status**: Pass
**Details**:

| Issue | Expectation | Observed Message | Result |
| --- | --- | --- | --- |
| Invalid API URL | Message that the API could not be reached | "Status 0: failed to connect to the API"| OK |
| API Offline | Message that the API could not be reached | "Status 404: failed to connect to the API"| OK |
| Invalid username | Message that user name and/or password are incorrect | "Login failed. please check your username and password and API configuration" | OK |
| Invalid password | Message that user name and/or password are incorrect | "Login failed. please check your username and password and API configuration" | OK |
| No officer for that user | Message that the account is not associated with an officer and cannot log in | "Failed to get officer details." | OK |
