### ISSUE TITLE
Infra layer symbol not always respecting HasIssues

### ISSUE THREAD

**Issue by Timothy-D** [exeGesIS-SDM/CAMS-Mobile#101]
Observed the following in 4.4.9, similar symptoms may occur from other paths.
1. Create a new furniture item on the tablet
2. Sync data
3. Accept the record in CAMS Desktop
4. In CAMS Desktop, add a new issue to the furniture item and save.
5. Sync data
6. On the tablet, the furniture item will show on the map without the ! decoration, but the issue shows on the furniture form.
7. At this point, vieWebInfra has an up-to-date LastUpdatedDate which should have come down in the sync, and HasIssues = 1. Also checked the tablet database and that is showing HasIssues = 1 as well.

**Comment by am-esdm** [comment]
Tested in Android v5.1.1 with Samsung Galaxy Tab A device, using the same data as TD above: the problem didn't seem to occur in that setup. Where clients have reported this problem too, they are also using Android v9 (possibly Android v8 too) on the Samsung Galaxy Tab Active 2 device

**Comment by LaineS** [comment]
Note: CAMS.css line 1638, see icon-has-issues (should be background: url(resources/icons/IssueIcons/Issue.png);). Check on Android 5.1

**Comment by am-esdm** [comment]
**CAMS Mobile version:** v4.4.10
**Sync account:** xgWCP
**Tablet:** Samsung Galaxy Tab A
**Android version:** v5.1.1

**Result:**
Pass: Similarly to my test with Android v5.1.1 (Tab A device) before v4.4.10 was produced, I haven't seen this problem so far on this Android/tablet setup with v4.4.10, seems ok so far from light basic testing. Key focus here is going to be to test on Android v8/9 on a Samsung Galaxy Tab Active 2

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.10
**Sync Account**: xgWCP
**Status**: Pass
**Details**: /!\ decorations now appearing on furniture items. Tested scenario above and decoration appeared OK. Added a new issue to an existing furniture item on the tablet, and decoration appeared immediately.

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.11
**Sync Account**: xgWCP
**Status**: Pass
**Details**: /!\ decorations now appearing on furniture items. Tested scenario above and decoration appeared OK. Added a new issue to an existing furniture item on the tablet, and decoration appeared immediately.

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.12
**Sync Account**: xgwcp
**Status**: Pass

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.13
**Sync Account**: xgWCP
**Status**: Pass
