### ISSUE TITLE
Android 10 compatibility

### ISSUE THREAD

**Issue by Timothy-D** [exeGesIS-SDM/CAMS-Mobile#103]
The Tab Active 3 is the replacement for our standard device. This runs android 10.
* CAMS Mobile 4.4.13 is our latest version. This targets android API 29 which corresponds to android 10. This does NOT work on the Active 3.
* CAMS Mobile 4.4.7 is the previous release version. This targets android API 28, which corresponds to android 9. This DOES work on the Active 3.

Need to make sure we are compatible with android 10 on the Tab Active 3

**Comment by LaineS** [comment]
v4.4.15 working on Android 9 (tested via the emulator) and Android 10 (using the Samsung Tab 3)
https://appcenter.ms/orgs/ESDM/apps/CAMSMobile/distribute/releases/109

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 3
**OS Version**: Android 10
**App Version**: 4.5.0
**Sync Account**: N/A
**Status**: FAIL
**Details**: App installs OK, but when you try to start it, the loading screen appears, there is a prompt to allow access to location, then the app closes itself. Unable to progress beyond here.

Note that this problem does not occur in the android 10 emulator.

**Comment by LaineS** [comment]
New version 4.5.1 should fix this (tested on the real Galaxy Tab 3 device and the Galaxy 2 emulator)

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 3
**OS Version**: Android 10
**App Version**: 4.5.1
**Status**: Pass
**Details**: v4.5.1 starts OK in android 10

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 3
**OS Version**: Android 10
**App Version**: 4.5.2
**Sync Account**:
**Status**: FAIL
**Details**: App crashes immediately on startup on the android 10 tablet. App installs OK, but when you try to start it, the loading screen appears, there is a prompt to allow access to location, then the app closes itself.

Will test on a10 emulator

**Comment by Timothy-D** [comment]
Tested on the A10 emulator - problem does not occur here, it is visible on the actual device

**Comment by Timothy-D** [comment]
Tested on Active 3 - OK
