### ISSUE TITLE
Remove option to "remove parent" when adding features

### ISSUE THREAD

**Issue by Timothy-D** [exeGesIS-SDM/CAMS-Mobile#107]
As the parent fields can no longer be edited due to the changes for #69 if the user removes the parent, the item then has no parent and cannot be saved - this is not a good experience and it would be best not to give them this option.

**Comment by LaineS** [comment]
Fixed

**Comment by Timothy-D** [comment]
**Device**: Emulator
**OS Version**: Android 10
**App Version**: 4.5.5
**Sync Account**: xgDev
**Status**: Pass
**Details**: Added furniture & issues to links & land. No option to remove parent - OK

**Comment by Timothy-D** [comment]
**Device**: Samsung Tab Active 3
**OS Version**: Android 10
**App Version**: 4.5.5
**Sync Account**: xgDev
**Status**: Pass
**Details**: Added furniture & issues of different geometry types to links & land. No option to remove parent - OK
