### ISSUE TITLE
Unable to select links the cross land parcels

### ISSUE THREAD

**Issue by Timothy-D** [exeGesIS-SDM/CAMS-Mobile#109]
Scenario: you have a land polygon on the map, and a link (line) crosses the polygon. You tap on the line but instead of selecting the link, it selects the land parcel.
However, if you go to the layer control and turn off the land layer and turn it back on again, you then _can_ select the link.

It looks like maybe when the land layer is removed & re-added, it's appearing in a different z-position. It would be better if it always appeared so that links were above and could be selected.

Not the highest priority as there is an easy workaround, but it's not ideal and it would be good to address

**Comment by LaineS** [comment]
v4.5.2

This is partially fixed, the land layer should now be at the bottom of the layer list. We use quite an old layer of leaflet though and there are some issues and sometimes it doesn't get placed at the bottom. It should behave better than it currently is though.

**Comment by Timothy-D** [comment]
**Device**: Emulator
**OS Version**: Android 8.1
**App Version**: 4.5.2
**Sync Account**: xgDev
**Status**: Mixed
**Details**: Some improvement, but it does seem a bit hit and miss. Further testing needed.

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 3
**OS Version**: Android 11
**App Version**: 4.5.3
**Sync Account**: xgDev
**Status**: Pass
**Details**: Easier with stylus and if zoom in further. OK
