### ISSUE TITLE
Selection and parenting problems

### ISSUE THREAD

**Issue by Timothy-D** [exeGesIS-SDM/CAMS-Mobile#110]
First noticed in 4.5.2 on 8.1 emulator. Not sure if this relates to changes made for #109 or #106 but I'm seeing that the parent doesn't always update when a new feature is tapped by the user:

1. Go to the map in CAMS Mobile
2. Tap a link, it highlights in yellow and the info pop-up appears. Make a note of the code
3. Tap another link, the highlight doesn't change but the pop-up appears against this second link. Make a note of the code
4. Tap the Add furniture button and tap the map to place the furniture item
5. Note the parent code that is displayed - you will see that this is the code of the first link you tapped (step 2), not the most recent

If after step 2 you tap off the link to deselect it, then when you tap the subsequent link it seems to get the selection correctly. In previous versions you could just select another link without having to de-select the first. This could lead to bad data if people don't notice the parent code

**Comment by LaineS** [comment]
Should be fixed in v4.5.3

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 3
**OS Version**: Android 11
**App Version**: 4.5.3
**Sync Account**: xgDev
**Status**: Pass
**Details**: OK
