### ISSUE TITLE
Tasks List Jobs view record button doesn't work

### ISSUE THREAD

**Issue by Timothy-D** [exeGesIS-SDM/CAMS-Mobile#115]
records in the Tasks list may relate to issues, jobs or routes. If you select a record that is an issue or a route, the view record button (top of the right toolbar) opens the form for that record. If you select a record that is a job and click that button, nothing happens. it should open the form for the job.

**Comment by LaineS** [comment]
Can you provide steps on how to replicate this (what issues to tap that have the right data etc)? Possibly create data in the training database.

**Comment by Timothy-D** [comment]
To replicate:
1. Sync xgDev config
2. Make sure you are logged in as esdm
3. Sync data
4. Tap the Tasks button to go to the tasks list
5. Tap the first "footpath" entry in the list - this should expand and there should be 2 jobs under it
6. Tap one of teh job entries to select it
7. Tap the grid button. This should show the form for that job, but it does nothing.

![image](https://user-images.githubusercontent.com/25226464/190386536-457ed991-40cf-484d-821f-8ba3280dfa51.png)

Note:
the xgDev config uses the same database as the internal config, but there may be some entries missing from the internal config. You need to have the following:

``` Diff
G_STATUS_LUT_ARRAY = [
    { uid: 1, tableName: 'Maint', code: 0, description: 'Unknown', displayColor: '' },
    { uid: 2, tableName: 'Maint', code: 1, description: 'Resolved', displayColor: 'Green' },
    { uid: 3, tableName: 'Maint', code: 2, description: 'Part Resolved', displayColor: 'Orange' },
    { uid: 4, tableName: 'Maint', code: 3, description: 'Unresolved', displayColor: 'Red' },
    { uid: 5, tableName: 'Route', code: 1, description: 'Part surveyed - access problem', displayColor: 'Orange' },
    { uid: 6, tableName: 'Route', code: 2, description: 'Part surveyed - not found', displayColor: 'Orange' },
    { uid: 7, tableName: 'Route', code: 3, description: 'Part surveyed - other', displayColor: 'Orange' },
    { uid: 8, tableName: 'Route', code: 4, description: 'Part surveyed - to be continued', displayColor: 'Orange' },
    { uid: 9, tableName: 'Route', code: 5, description: 'Not surveyed', displayColor: 'Red' },
    { uid: 10, tableName: 'Route', code: 6, description: 'Whole link surveyed', displayColor: 'Green' },
    { uid: 11, tableName: 'Route', code: 7, description: 'Part surveyed - expert advice required', displayColor: 'Orange' },
    { uid: 12, tableName: 'Infra', code: 1, description: 'Outstanding (test status)', displayColor: 'Orange' },
    { uid: 12, tableName: 'Infra', code: 5, description: 'Not started (test status)', displayColor: 'Red' },
    { uid: 12, tableName: 'Infra', code: 11, description: 'Could not complete (test status)', displayColor: 'Red' },
    { uid: 13, tableName: 'Infra', code: 23, description: 'Partly done (test status)', displayColor: 'Orange' },
    { uid: 14, tableName: 'Infra', code: 24, description: 'Outstanding (test status)', displayColor: 'Green' },
+    { uid: 15, tableName: 'Job', code: 1, description: 'Complete', displayColor: 'Green' },
+    { uid: 16, tableName: 'Job', code: 0, description: 'Outstanding', displayColor: 'Red' }
];

```

**Comment by LaineS** [comment]
Fixed

1. Sync data and open Tasks
2. Select a task where its a type=Job
3. Tap to open, edit data and save
4. Upload and process data
5. Sync, make sure it's processed correctly and updated on the device correctly
6. Do the same with a new job on an issue (just to make sure this still works)

**Comment by Timothy-D** [comment]
**Device**: Emulator
**OS Version**: Android 10
**App Version**: 4.5.5
**Sync Account**: xgdev
**Status**: FAIL - Unable to test
**Details**:
Installed v5.4.5 and synced xgDev config. Logged in as esdm. No Jobs appear in the task list. 🐞 

Installed v4.5.3 and synced xgDev config. Logged in as esdm. Jobs appear in the task list. OK.
Installed v4.5.4 and synced xgDev config. Logged in as esdm. Jobs appear in the task list. OK.

No changes to data or config files between the above

This suggests that something has changed between 4.5.4 and 4.5.5 which is stopping the Jobs appearing in the list.

**Comment by Timothy-D** [comment]
**Device**: Emulator
**OS Version**: Android 10
**App Version**: 4.5.4
**Sync Account**: xgdev
**Status**: Info
**Details**: Installed v4.5.4 and synced xgDev config. Logged in as esdm. Jobs appear in the task list. Can select a job in the task list and click the button to view the record. Seems OK in this version. **However in v4.5.5 the jobs don't appear in the task list at all**.

**Comment by LaineS** [comment]
To test, jobs=complete are not shown in the task list

**Comment by Timothy-D** [comment]
Not convinced about this one. I have set up a couple of jobs assinged to my user in CAMS Desktop, eg 11:
![image](https://user-images.githubusercontent.com/25226464/194364972-b4f0ea18-0a4b-4d59-a72e-8f7ce4cabdf3.png)

This appears in the database after being synced to the tablet:
![image](https://user-images.githubusercontent.com/25226464/194365569-922fd9e8-6fbb-4a93-bef8-a3fd2044baae.png)

However, no jobs appear in the list on the tablet:
![image](https://user-images.githubusercontent.com/25226464/194366027-68883bcc-2dab-41d5-9a7b-42719c85e5a6.png)

**Comment by Timothy-D** [comment]
Looked into this a bit further. With 5.4.4 installed, using the same config & database, I get Jobs appearing in the app:
![image](https://user-images.githubusercontent.com/25226464/194367925-0efbd053-3ddd-479e-ac83-58ab1d48a4fe.png)

So there looks to be something different between 5.4.4 & 5.4.5 
I spotted this in the GIT revision history (commit 3c046e8a):
```diff
        //load the store before adding the accordion otherwise we start with the empty list message and then the list magically displays
-       if (G_JOBS_ENABLED==false) workListStore.getProxy().FILTER_STR = " WHERE NOT worklist.TableName='Job'"; // Filter out jobs if not enabled
+		var filterStr = "";
+       if (G_JOBS_ENABLED==false) filterStr = " WHERE NOT worklist.TableName='Job'"; // Filter out jobs if not enabled
+		else filterStr = " WHERE NOT worklist.StatusFieldName='Complete'";
+		workListStore.getProxy().FILTER_STR = filterStr;
		workListStore.load({
            callback: function (records, operation, success) {
                self.listViewContainer.add(accordionList);
```

Looking at this section
```js
if (G_JOBS_ENABLED==false) filterStr = " WHERE NOT worklist.TableName='Job'"; // Filter out jobs if not enabled
else filterStr = " WHERE NOT worklist.StatusFieldName='Complete'";
```
If I understand it correctly then if Jobs are enabled, the filter removes everything where `worklist.TableName='Job'`, otherwise, (ie if jobs ARE enabled) the filter removes everything where the `worklist.StatusFieldName='Complete'` - However, the `StatusFieldName` column holds the name of the true status field in the parent table. For Jobs this is Job.Complete, therefore jobs are getting filtered out from the Task List when Jobs are enabled.

@LaineS I think we need to discuss this quickly tomorrow (7/10)

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 3
**OS Version**: Android 10
**App Version**: 4.5.6
**Sync Account**: xgdev
**Status**: Pass ✔️
