### ISSUE TITLE
Add option to hide Jobs in CAMS mobile

### ISSUE THREAD

**Issue by Timothy-D** [exeGesIS-SDM/CAMS-Mobile#116]
Add a config setting to allow the Jobs to be hidden in the UI. The current Job structure on CAMS Mobile is not compatible with the changes made in CAMS Pro, and simply hiding this area of the system is the easiest way to avoid compatibility issues (a later Mobile version will address the Jobs issue fully). Also, as Jobs are not used by everyone, and not everyone will have this module in CAMS Pro, the ability to hide Jobs will avoid confusion.

When Jobs are configured to be hidden, the following elements should be hidden in the UI:
- Jobs button on Issue form
- Jobs sync entry
- Jobs in Task List

**Comment by Timothy-D** [comment]
@LaineS please can you note what the config setting should be so I can add to my config file and test?

**Comment by LaineS** [comment]
// Enable or Disable Jobs
G_JOBS_ENABLED = true;

**Comment by Timothy-D** [comment]
**Device**: Emulator
**OS Version**: Android 10
**App Version**: 4.5.5
**Sync Account**: xgdev
**Status**:
**Details**:

| Setting | Task List | Add Button | Job Grid | Sync button |
| --- | --- | --- | --- | --- |
| `true` | Jobs don't appear (see #115) 🐞 | Button shows and works ✔️ | Grid shows and works ✔️ | Button shows and works ✔️ |
| 'false' | Jobs don't appear ✔️ | Button is not visible ✔️ | Grid is not visible ✔️ | Button shows and works 🐞 |

The issue of jobs not appearing in the task list is covered under #115 as it was first spotted when testing that. I'm cautious about interfering with the sync behaviour as I know this is a complex area and i think for this version I'm happy to let this go, particularly as other items are higher priority.

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 3
**OS Version**: Android 10
**App Version**: 4.5.6
**Sync Account**: xgdev
**Status**: Pass
**Details**:

| Setting | Task List | Add Button | Job Grid | Sync button |
| --- | --- | --- | --- | --- |
| `true` | Jobs Appear OK | Button shows and works ✔️ | Grid shows and works ✔️ | Button shows and works ✔️ |
| `false` | Jobs don't appear ✔️ | Button is not visible ✔️ | Grid is not visible ✔️ | Button shows and works 🐞 |

As above, hapy with this for now
