### ISSUE TITLE
Update CAMS Mobile libraries, etc

### ISSUE THREAD

**Issue by LaineS** [exeGesIS-SDM/CAMS-Mobile#117]
Open the solution, compile and general maintenance update. This is required before we do any additional work

**Comment by LaineS** [comment]
* Solution compiles and debug app installs ok on Android tablet
*

**Comment by LaineS** [comment]
Ready to test

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 3
**OS Version**: Android 10
**App Version**: 4.5.5
**Sync Account**: xgWcp
**Status**:
**Details**:

  - [X] Can login - OK ✔️ 
  - [X] Can download config- OK ✔️ 
  - [X] Can download data- OK ✔️ 
  - [X] Can see data on map - OK ✔️ 
  - [ ] GPS location works
  - [ ] GPS tracking works
  - [ ] Offline maps work
  - [X] Check photo download works - no error messages, but don't display 🐞 See #118 
  - [ ] Can edit & save data
  - [ ] Can capture & link photos
  - [ ] Can Add new records
  - [ ] Can upload data & photos
