### ISSUE TITLE
Expand variety of icons available for CAMS Mobile 

### ISSUE THREAD

**Issue by richardcesdm** [exeGesIS-SDM/CAMS-Mobile#120]
Not suggesting to replace the current icons, just expand the variety available as it is a bit lacking. I have uploaded a copy of the set we are currently using across CAMS Pro / CAMS Web: 

[Icons.zip](https://github.com/exeGesIS-SDM/CAMS-Mobile/files/10697314/Icons.zip)

Maybe these could be loaded into a new folder within the current CAMS Mobile icons folder? Could call the folder 2023Icons i.e. so we'd be using folder path like resources/icons/2023Icons in the CAMSMobileMapThemeConfig 
(exact folder name doesn't matter as long as it is distinct and someone tells me what it is so I know how to reference it)

**Comment by Timothy-D** [comment]
These icons are already available in CAMS Mobile, under resources/icons/purple. There are another set under resources/icons/green
