### ISSUE TITLE
Automatically Derive Issue Type from Furniture Type

### ISSUE THREAD

**Issue by Timothy-D** [exeGesIS-SDM/CAMS-Mobile#22]
Currently when you add an issue to a furniture item in CAMS Mobile, you have to manually select the issue type. This can be a pain for users and in the Desktop system the issue type is automatically determined. This should happen in the mobiel app too.

The InfraTypeLUT for furniture also contains a field that defines the default Maint (issue) type for a furniture item of that type. This is then used by CAMS to pre-populate the issue type field when an issue is created on a furniture item. This field needs to be synchronised down to the mobile app so that it can use it to calculate the issue type in the same way as the desktop application.

The complication is that currently the mobile app expects all the LUTs to have the same structure, and this will require a structure change to the InfraTypeLUT

**Comment by LaineS** [comment]
Added a new setting to CAMSMobile.Config, this tells the app to set the default maint code when when creating a new issue from with a furniture parent:

e.g. 
`
G_FURNITURE_DEFAULTISSUETYPE_LIST =[
	{ InfraType: "1", DefaultIssueType: "I1/0" }
]
`

1. Open a furniture item
2. Select a type and subtype that is on the list above, select "Unsatisfactory" from the condition menu
3. When you save the issue form should open with the correct default maint codes set

**Comment by Timothy-D** [comment]
**Device**: Emulator
**OS Version**: Android 8
**App Version**: 4.5.0
**Sync Account**: xgdev
**Status**: Pass
**Details**: Added settings to config file, When creating issue on furniture, issue type is automatically derived, matching furniture type.

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 3
**OS Version**: Android 10
**App Version**: 4.5.1
**Sync Account**: xgdev
**Status**: Pass
**Details**: Added settings to config file, When creating issue on furniture, issue type is automatically derived, matching furniture type.
