### ISSUE TITLE
CM 4.3.7 + Stop TextArea UDF type from overlapping with UDF label (see example)

### ISSUE THREAD

**Issue by richardcesdm** [exeGesIS-SDM/CAMS-Mobile#45]
Currently the default size of the TextArea UDF type is overlapping with the label for the UDF. Example: 

![image](https://user-images.githubusercontent.com/24268198/56374036-36c35500-61fa-11e9-9ff7-cce3e90f0e97.png)

Full text of the label should say 'PeachTextArea' but it is getting cut off. Fairly minor but would be good to reduce the TextArea UDF size so that it is the same size as the TextBox UDF (e.g. like the 'BananaTextBox' field.

**Comment by LaineS** [comment]
Fixed in v4.3.10, the text area now aligns correctly

**Comment by am-esdm** [comment]
Have tested on older device (Samsung Galaxy Tab A), but not the Samsung Galaxy Tab Active yet. Seems to be resolved on the older device

**Comment by am-esdm** [comment]
Tested on Samsung Galaxy Tab Active 2 as well now, looks fine on there too

**Comment by am-esdm** [comment]
Now tested in v4.3.11 using the Samsung Galaxy Tab Active 2 device (on Android v8.1), seems to be working fine on that device now. Need to test on the older Samsung Galaxy Tab A device and pass to the wider CAMS Team for more varied testing before this can be signed off
