### ISSUE TITLE
Adding a invalid cost to a new issue leads to the value breaking on new issues

### ISSUE THREAD

**Issue by richardcesdm** [exeGesIS-SDM/CAMS-Mobile#46]
Steps to reproduce: 
1. Create new issue, record cost of '9.9.9'
2. Save issue (cost is saved as valid)
3. Create another new issue, check cost
4. Cost on new issue will display '9.9.9' same as original issue with broken cost

Suggested changes: 
- Validate cost field to prevent this type of value from being inserted (should allow valid decimals only)
- (If necessary, if the above change does not prevent this) Stop the cost value from being inherited from one new issue to the next.

**Comment by Timothy-D** [comment]
Maint.TotalCost field is `Real` format - ensure uploaded data are compatible with this

**Comment by LaineS** [comment]
I cannot replicate Richards issue at all, can you confirm this is still a problem in at least v4.4.13?

Not sure what your comment means Timothy

**Comment by richardcesdm** [comment]
hello, been catching up on emails after leave and got notified on this one. Since I reported it I figured it would be quick for me to retest it. I have just retested and using android device Samsung Galaxy Tab A(6) (Model: SM-T280) running Android v5.1.1 (a device still widely used by many clients) this is still a problem. Will leave it up to TD / LS as to whether this is worth pursuing further.

**Comment by Timothy-D** [comment]
**Device**: Emulator
**OS Version**: Android 8
**App Version**: 4.5.0
**Sync Account**: xgdev
**Status**: Fail
**Details**: 
Followed Richard's steps above, able to replicate the issue as described.
1. Create new issue, record cost of '9.9.9'
2. Save issue (cost is saved as valid)
3. Create another new issue, check cost
4. Cost on new issue will display '9.9.9' same as original issue with broken cost

**Comment by Timothy-D** [comment]
**Device**: Emulator
**OS Version**: Android 10
**App Version**: 4.5.2
**Sync Account**: xgDev
**Status**: Pass with question
**Details**:
1. Create new issue, record cost of '9.9.9'
2. Save issue - no warning about invalid
3. Create another new issue, check cost
4. Cost on new issue is empty - OK

Wonder whether it is possible to restrict the entry to valid numbers, but not sure how important this is. @richardcesdm what do you think?

**Comment by richardcesdm** [comment]
@Timothy-D  I think if we are not submitting invalid data that is the most important thing. In an ideal world, some feedback to advise the user the value they have recorded will not be saved would be very useful but I'd suggest that is a lower priority than some other issues so the dev resource may be better used elsewhere (e.g. the problem where you can't select paths running underneath a land parcel, if that is still outstanding)

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 3
**OS Version**: Android 11
**App Version**: 4.5.3
**Sync Account**: xgdev
**Status**: Pass
**Details**: unable to enter 9.9.9 in cost box, may be due to component update
