### ISSUE TITLE
Client Request: ability to split furniture layer

### ISSUE THREAD

**Issue by Timothy-D** [exeGesIS-SDM/CAMS-Mobile#48]
From Central Bedfordshire:

We wish to able to switch on/off the tree recorded (furniture) layer against the physical furniture items – the reason is that the screen / site looks very busy until you zoom in  to separate all the recorded furniture items.
 
We want it to operate it like switching on/off the PROW routes layers (have trees as a separate layer), would it also be possible to have the trees shown initially as a different colour when we have both layers switched.
 
We would be looking to have this update as part of the next service update in 2020.

**Comment by Timothy-D** [comment]
We have received an order from Central Beds to split the furniture layer based on group type. We only need to apply this to this one layer, I don't think this is the place to define how, but the requirements are:
1. Somewhere, eg in the InfraTypeLUT or the config file, I will be able to define a sub-layer for each Infra Type.
2. When I run CAMS Mobile, the different furniture items will be drawn on the different sub-layers
3. I will be able to turn these layers on and off independantly

**Comment by Timothy-D** [comment]
Agreed approach:
1. Number of map sub-layers is not limited, but this applies to Infra (furniture) only
1. Within the map theme config file, I can define two or more sub layers to draw the features on, and against each one put in a list of the group types that should be drawn on that layer.
1. If no sublayers are specified, all are drawn on the one Furniture layer as now.
1. If only one single sublayer is specified, all are drawn on the one Furniture layer as now.
1. Within the map layer control, the sublayers will all appear under the furniture layer and can be turned on or off individually
1. The current furniture layer will appear as a parent and can be used to turn all the sub layers on or off together.

**Comment by am-esdm** [comment]
> Agreed approach:
> 
> 1. Number of map sub-layers is not limited, but this applies to Infra (furniture) only
> 2. Within the map theme config file, I can define two or more sub layers to draw the features on, and against each one put in a list of the group types that should be drawn on that layer.
> 3. If no sublayers are specified, all are drawn on the one Furniture layer as now.
> 4. If only one single sublayer is specified, all are drawn on the one Furniture layer as now.
> 5. Within the map layer control, the sublayers will all appear under the furniture layer and can be turned on or off individually
> 6. The current furniture layer will appear as a parent and can be used to turn all the sub layers on or off together.

Edit to '6': ...But the toggle on/off of the parent Furniture layer will retain the previously ticked/unticked visibilities of each child Furniture layer

Additional '7': The app will remember the last-used settings when it is restarted

**Comment by LaineS** [comment]
Config: 
A new mandatory config value must be specified in CAMSMobileMapThemeConfig. It can be set to allow all furniture items to be shown on the map (i.e. as things currently work):
G_FURNITURE_MAP_GROUPLAYERS = [];

You can also specify which furniture map groups layers to show in the app:
G_FURNITURE_MAP_GROUPLAYERS = [
	{
		name: 'Alongside and Amenities',
		typedescrlist: ['Alongside', 'Amenity'],
		visible: false
	},
	{
		name: 'Gates and stuff',
		typedescrlist: ['Gate'],
		visible: true
	}
];

**Comment by Timothy-D** [comment]
Installed v 4.3.13 (should be 4.4.1) on Samsung Tab Active 2 (android 9)
Crashes almost immediately on start up, unable to test.
No error messages or any useful feedback

**Comment by Timothy-D** [comment]
Confirming that version 4.3.11 on the same tablet is stable

**Comment by am-esdm** [comment]
Carried out initial config test (Tab A, Android v5.1.1) - added the following to the xgWCP sync account's 'CAMSMobileMapThemeConfig_xgWCP.js' config file, below all the existing config entries: 

G_FURNITURE_MAP_GROUPLAYERS = [
{
name: 'A to B',
typedescrlist: ['Alongside', 'Amenity', 'Barrier', 'Boardwalk', 'Bridge'],
visible: true
},
{
name: 'C to 0',
typedescrlist: ['Crossing', 'Drain', 'Fence', 'Gate', 'Other'],
visible: true
},
{
name: 'S',
typedescrlist: ['Sign', 'Sign-NotQS', 'Steps', 'Stile'],
visible: true
}
];

Then, having already been synced to the xgWCP sync account, I resynced the config files via the Sync Status window > syncing just the 'Config Files' row, using the same xgWCP sync code, then went to the map window and the new Furniture Group Layers map setup hadn't come through as configured, it was still showing the two Furniture layers LS configured to start with, rather than the three layers configured above. Closing and re-starting the app didn't make any difference.

Then as advised by LS, reinstalled the app. When doing so, as per our normal upgrade or reinstall procedure I removed the SD card before uninstalling the existing app. After putting the SD card back in I also deleted the existing synced 'xgWCP' config files, to make sure the app wouldn't be using any old xgWCP config files, then opened the app which was at that point using its default config, and synced the xgWCP config. Then went to the map and the app had at that point picked up the new map configuration.

**Comment by am-esdm** [comment]
Tab A, Android v5.1.1: When you open the Map Layers Control window, you can't scroll down (or up) within the list to see the layers lower down the list that have been pushed off screen by the newly configured Furniture Group layers. E.g. I've added the three groups described above, and that has pushed most of the 'Tasks' layer row off the bottom of the screen

**Comment by am-esdm** [comment]
Tab A, Android v5.1.1: Using the xgWCP sync account and the configuration described above (3 furniture group layers), if you view the map at the default start location (Bangor), then zoom in using the magnifying glass '+' option twice (to view furniture and issue records) and pan the map just slightly to the north to see the Link Routes (and associated Furniture and Issues) around the 'Garth' coastal area at the north end of Bangor, then go to the Map Layers Control window, initially all the layers and sub layers will be ticked on as expected. Next untick the 'A to B' first sub layer, then the same for the 'C to O' and 'S' sub layers (but leave the parent Furniture layer turned on), then go back to the map. Map features with a signpost icon (group type = 'Sign', falling under the configured 'S' sub layer) are still showing, when no furniture features should now be showing [this is Problem 1]. If you then go back into the Map Layers Control window and re-tick the sub layers in reverse order, i.e. ticking 'S' then 'C to O' then 'A to B' (with the parent Furniture layer still ticked on), then go back to the map, the furniture features all double up to display duplicate records for each item of furniture, creating lots of blue feature aggregation bubbles and duplicate records [this is Problem 2]

**Comment by am-esdm** [comment]
Getting a lot of Route features, and some Furniture and Issue features, disappearing (and thereby becoming unselectable too) as I pan around the map - see https://github.com/exeGesIS-SDM/CAMS-Mobile/issues/52 as this seems to be the same thing

**Comment by am-esdm** [comment]
Further item: depending on which layer you have most recently ticked to display, the Route lines and any Furniture Lines jump above each other - there should be a consistent layer order. There looks to be some overlap with this GitHub Issue here: https://github.com/exeGesIS-SDM/CAMS-Mobile/issues/13 - which has a sensible suggestion to work around the overlapping line feature problem, but there is still a second problem here of layer draw order (some possible overlap (no pun intended!) there also with: https://github.com/exeGesIS-SDM/CAMS-Mobile/issues/57)

**Comment by am-esdm** [comment]
Tab A, Android v5.1.1: Starting from the context of having all furniture group layers ticked when the app is started, if you go to the Map Layers Control window, untick the 'A to B' first sub layer, then the same for the 'C to O' and 'S' sub layers (but leave the parent Furniture layer turned on), then go back to the map. As reported above, map features with a signpost icon (group type = 'Sign', falling under the configured 'S' sub layer) are still showing, when no furniture features should now be showing - if you then go back into the Map Layers Control window and re-tick the sub layers in the same order, 'A to B', then 'C to O', then 'S', then untick the parent Furniture layer, then go back to the map, some furniture map features still display, when there shouldn't be able displaying as you've turned off the overall Furniture layer

**Comment by LaineS** [comment]
1. When the user clears all data, the app now also clears the furniture map layer config (so if you change this on the server and then download to the app the new changes are then used. Previously they were not and you had to uninstall the app)

2. Added a vertical scroll bar to the map layer control

**Comment by am-esdm** [comment]
As discussed #52 and #57 were already in the project (#52 was added earlier today as a result of our earlier discussion), and #13 would be a nice to have, but there are already a fair amount of tasks in the project, so let's leave #13 for now, then if there's any extra time available at the end of the project after the existing project's tasks list, we can consider that one

**Comment by LaineS** [comment]
In v4.4.0: 

1. When the user clears all data, the app now also clears the furniture map layer config (so if you change this on the server and then download to the app the new changes are then used. Previously they were not and you had to uninstall the app)

2. Added a vertical scroll bar to the map layer control

3. Fixed UI bug where the label name moved down slightly when you tap it

4. Added code to stop duplicate features being shown

5. Added a mask so when you change layer visibility it loads the data before letting you proceed. This should stop features in layers that are not visible being shown.

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab A
**OS Version**: Android 9
**App Version**: 4.4.0

New configuration takes effect when when data is reloaded - needs documenting as this is not intuitive, but OK.
Can set different layers in config, and seem to be able to toggle different layers on and off correctly.
layer control can be scrolled OK
Didn't notice text jumping around

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab A
**OS Version**: Android 9
**App Version**: 4.4.0
**Status**: Informational
**Details**: 
- Tested adding and editing items - this seemed OK; I can add a furniture item to a hidden layer without error, plotting is fine but of course it's not visible when the record is saved. I think this is fine as it is, and this is consistent with what happened previously when the full furniture layer was hidden, but it will need documenting. 
- Config seems to be being read OK, and I can toggle the sublayers on and off independently. The overall furniture layer visibility toggle seems OK too.
- Did not notice any duplication of features
- Message appears while map redraws, didn't notice any incorrect features showing
- Layer control scroll is fine (point 2 above), and text in there doesn't seem to move around (point 3 above)
-  Seems to be a glitch relating to display of features in other layers when a furniture sub layer is toggled on or off (probably relates to issue #52). See [FeatureDisplay_Issues48+52.zip](https://github.com/exeGesIS-SDM/CAMS-Mobile/files/4694611/FeatureDisplay_Issues48%2B52.zip) for images (put them here to make reading easier, steps below relate to the photo numbers):
    1. Map has two linear issues
    2. Open layer control and turn off one of the sub layers - "ROW Furniture" in this case.
    3. Return to the map - left issue has disappeared.
    4. Zoom out one notch - this issue reappears
    5. Zoom back in - feature still visible
    6. Open layer control and turn the sub layer back on, return to the map. Furniture sublayer is visible again but this issue has vanished
    7. Zoom out one notch - this issue reappears
- Layer order is not consistent - not very easy to explain, so will demonstrate with another series of photos - [Issue48b.zip](https://github.com/exeGesIS-SDM/CAMS-Mobile/files/4694705/Issue48b.zip), steps are:
    1.  Normal display with issues & furniture on top of the routes
    2. Turn off routes layer - as expected
    3. Turn Routes layer back on - now draws on top of the furniture and issue layers, meaning you can't select them

So remaining dev work for this looks to just be the feature display and layer order glitches

**Comment by am-esdm** [comment]
> **Device**: Samsung Galaxy Tab A
> **OS Version**: Android 9
> **App Version**: 4.4.0
> 
> New configuration takes effect when when data is reloaded - needs documenting as this is not intuitive, but OK.
> Can set different layers in config, and seem to be able to toggle different layers on and off correctly.
> layer control can be scrolled OK
> Didn't notice text jumping around

Hi @Timothy-D, please can can you confirm which device and Android combination this actually refers to, as the existing 'Tab A' and 'Android 9' combination doesn't seem to make sense? thanks

**Comment by am-esdm** [comment]
> **Device**: Samsung Galaxy Tab A
> **OS Version**: Android 9
> **App Version**: 4.4.0
> **Status**: Informational
> **Details**:
> 
> * Tested adding and editing items - this seemed OK; I can add a furniture item to a hidden layer without error, plotting is fine but of course it's not visible when the record is saved. I think this is fine as it is, and this is consistent with what happened previously when the full furniture layer was hidden, but it will need documenting.
> * Config seems to be being read OK, and I can toggle the sublayers on and off independently. The overall furniture layer visibility toggle seems OK too.
> * Did not notice any duplication of features
> * Message appears while map redraws, didn't notice any incorrect features showing
> * Layer control scroll is fine (point 2 above), and text in there doesn't seem to move around (point 3 above)
> * Seems to be a glitch relating to display of features in other layers when a furniture sub layer is toggled on or off (probably relates to issue #52). See [FeatureDisplay_Issues48+52.zip](https://github.com/exeGesIS-SDM/CAMS-Mobile/files/4694611/FeatureDisplay_Issues48%2B52.zip) for images (put them here to make reading easier, steps below relate to the photo numbers):
>   
>   1. Map has two linear issues
>   2. Open layer control and turn off one of the sub layers - "ROW Furniture" in this case.
>   3. Return to the map - left issue has disappeared.
>   4. Zoom out one notch - this issue reappears
>   5. Zoom back in - feature still visible
>   6. Open layer control and turn the sub layer back on, return to the map. Furniture sublayer is visible again but this issue has vanished
>   7. Zoom out one notch - this issue reappears
> * Layer order is not consistent - not very easy to explain, so will demonstrate with another series of photos - [Issue48b.zip](https://github.com/exeGesIS-SDM/CAMS-Mobile/files/4694705/Issue48b.zip), steps are:
>   
>   1. Normal display with issues & furniture on top of the routes
>   2. Turn off routes layer - as expected
>   3. Turn Routes layer back on - now draws on top of the furniture and issue layers, meaning you can't select them
> 
> So remaining dev work for this looks to just be the feature display and layer order glitches

Hi @Timothy-D, please can can you confirm which device and Android combination this actually refers to, as the existing 'Tab A' and 'Android 9' combination doesn't seem to make sense? thanks

**Comment by am-esdm** [comment]
thanks Timothy

**Comment by am-esdm** [comment]
> Tab A, Android v5.1.1: Using the xgWCP sync account and the configuration described above (3 furniture group layers), if you view the map at the default start location (Bangor), then zoom in using the magnifying glass '+' option twice (to view furniture and issue records) and pan the map just slightly to the north to see the Link Routes (and associated Furniture and Issues) around the 'Garth' coastal area at the north end of Bangor, then go to the Map Layers Control window, initially all the layers and sub layers will be ticked on as expected. Next untick the 'A to B' first sub layer, then the same for the 'C to O' and 'S' sub layers (but leave the parent Furniture layer turned on), then go back to the map. Map features with a signpost icon (group type = 'Sign', falling under the configured 'S' sub layer) are still showing, when no furniture features should now be showing [this is Problem 1]. If you then go back into the Map Layers Control window and re-tick the sub layers in reverse order, i.e. ticking 'S' then 'C to O' then 'A to B' (with the parent Furniture layer still ticked on), then go back to the map, the furniture features all double up to display duplicate records for each item of furniture, creating lots of blue feature aggregation bubbles and duplicate records [this is Problem 2]. A further product of this same process is the creation of duplicate Issue map features too [this is Problem 3]

Device: Samsung Galaxy Tab A
OS: Android v5.1.1
CAMS Mobile version: v4.4.0

Having re-tested these problems, I haven't seen any of them reappear in v4.4.0

**Comment by am-esdm** [comment]
> Tab A, Android v5.1.1: When you open the Map Layers Control window, you can't scroll down (or up) within the list to see the layers lower down the list that have been pushed off screen by the newly configured Furniture Group layers. E.g. I've added the three groups described above, and that has pushed most of the 'Tasks' layer row off the bottom of the screen. Also when you first open the app (e.g. after closing it), open this Map Layers Control window and click some of the layers (e.g. 'Issue' and 'Route'), the layer's text name label jumps slightly down, can this be stabilised?

Device: Samsung Galaxy Tab A
OS: Android v5.1.1
CAMS Mobile version: v4.4.0

Having re-tested these problems, I haven't seen any of them reappear in v4.4.0

**Comment by am-esdm** [comment]
> Tab A, Android v5.1.1: Starting from the context of having all furniture group layers ticked when the app is started, if you go to the Map Layers Control window, untick the 'A to B' first sub layer, then the same for the 'C to O' and 'S' sub layers (but leave the parent Furniture layer turned on), then go back to the map. As reported above, map features with a signpost icon (group type = 'Sign', falling under the configured 'S' sub layer) are still showing, when no furniture features should now be showing - if you then go back into the Map Layers Control window and re-tick the sub layers in the same order, 'A to B', then 'C to O', then 'S', then untick the parent Furniture layer, then go back to the map, some furniture map features still display, when there shouldn't be any displaying as you've turned off the overall Furniture layer (note this is intermittent, and you may have to play around with a similar scenario a few times to get this to happen, but it usually occurs within around 30 seconds of playing around with the map layer settings, returning to this described end setup each time to try to replicate it)

Device: Samsung Galaxy Tab A
OS: Android v5.1.1
CAMS Mobile version: v4.4.0

Having re-tested this problem, I haven't seen it reappear in v4.4.0

**Comment by am-esdm** [comment]
**Device**: Samsung Galaxy Tab A
**OS**: Android v5.1.1
**CAMS Mobile version**: v4.4.0

With regarding to LS' comment: "When the user clears all data, the app now also clears the furniture map layer config" - I haven't found this to be the case (which is fine actually, but worth clarifying), when I run the clear data routine it seems to retain the furniture groups config.

Also noticed that, as long as you have the new furniture groups config included in the relevant config files for the different sync accounts (that can be in the default format of just a single layer), the app seems to pick up the new sync account's furniture group config when you sync across to a different config account (e.g. going from 'xgWCP' to 'xgEastSus') but without syncing the new survey data on that 2nd account, and that seems to be the case either when you clear the survey data from the the first account before syncing across to the second account, or if you had data synced on the first account and you didn't clear it before syncing across to the 2nd account. So that seems to contrast with TD's previous statement:

"New configuration takes effect when when data is reloaded - needs documenting as this is not intuitive, but OK." - perhaps (?) this is because:

1. The sync account(s) TD was using may not have had the new required config added? E.g. I added the required config to the xgdev and xgEastSus accounts today

2. Or @Timothy-D were you referring to e.g. _adding/removing_ a new furniture group to the config, rather than just syncing an accounts configuration? As that's a different context

**Comment by Timothy-D** [comment]
Scenario here was as follows:
1. App installed - used the built-in config. Furniture Layers = "A-B"/"C-O"/"S"
2. Synced Central Bedfordshire config (auto restart app) - setting not present. Furniture Layers = "A-B"/"C-O"/"S"
3. Log out and log in with CBC account. Furniture Layers = "A-B"/"C-O"/"S"
4. Synced Central Bedfordshire data  - OK. Config file unchanged, groups setting not present. Furniture Layers = "A-B"/"C-O"/"S".
5. Updated MapThemeConfig file to include new furniture layer group settings for RoW Furniture, Site furniture & trees.
6. Restarted app with new config. Furniture Layers = "A-B"/"C-O"/"S"
7. Cleared data on tablet and re-synchronised (auto restart app). Furniture Layers = "ROW Furniture"/"Site Furniture"/"Trees"
8. Synced XG East Sussex config (auto restart app) - config has no layer groups configured. Furniture Layers = "ROW Furniture"/"Site Furniture"/"Trees"
9. Clear data. Furniture Layers = "ROW Furniture"/"Site Furniture"/"Trees"
10. Log out and log in with xg east sussex account. Furniture Layers = "ROW Furniture"/"Site Furniture"/"Trees"
11. Sync furniture data. Furniture Layers = "ROW Furniture"/"Site Furniture"/"Trees"
12. Restart app. Furniture Layers = single "Furniture" layer

**Comment by Timothy-D** [comment]
The above is not a major problem, as it is something that can be worked around. Remember that this was a specific request for one client, so I doubt many will be using this. Also, I expect that once set up it won't change very often.

What I do think needs addressing are:
1. Glitch with features not redrawing after turning sublayers on or off - probably linked to #52 
2. Glitch of layer order when turning layers on and off

Other than that, I think this is nearly there

**Comment by LaineS** [comment]
Thanks both, as per Timothy's last comment above. All issues look to be resolved with this issue now except for feature not drawing (#52) and layer order changing (I have logged this as #84). I will work on these two issues separately and move this issue into status=test.

Can you review and close the issue if there is nothing else left on it?
Ta
Laine

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.1
**Status**: PASS
**Details**:
Tested this issue:
> Seems to be a glitch relating to display of features in other layers when a furniture sub layer is toggled on or off (probably relates to issue #52). See FeatureDisplay_Issues48+52.zip for images (put them here to make reading easier, steps below relate to the photo numbers):
> 1. Map has two linear issues
> 1. Open layer control and turn off one of the sub layers - "ROW Furniture" in this case.
> 1. Return to the map - left issue has disappeared.
> 1. Zoom out one notch - this issue reappears
> 1. Zoom back in - feature still visible
> 1. Open layer control and turn the sub layer back on, return to the map. Furniture sublayer is visible again but this issue has vanished> 1. Zoom out one notch - this issue reappears

Not replicated, both issue features continue to appear on screen

Tested this issue:
> Layer order is not consistent - not very easy to explain, so will demonstrate with another series of photos - Issue48b.zip, steps are:
> 1. Normal display with issues & furniture on top of the routes
> 1. Turn off routes layer - as expected
> 1. Turn Routes layer back on - now draws on top of the furniture and issue layers, meaning you can't select them

Not replicated, routes redraw under furniture and can select OK (see also #57)

General testing: Able to toggle sub layers on and off independently, seems OK

**Comment by KathrynSteemson** [comment]
Device: Samsung Galaxy Tab A
OS: Android v5.1.1
CAMS Mobile version: v4.4.0

There is still some strange behaviour going on here as at one point I was seeing all Issues appearing twice. Trying to replicate this by switching layers on an off, not able to. Close app and re-start. Now seeing Issues appearing twice at the same location (points only).

Turn Issue layer off - display as expected
Turn furniture layer off - display as expected
Turn route layer off - display as expected
Turn issues back on - now only see 1 item, so layer has fixed itself
Other layers switch on - layer remains correct.

I don't seem to be able break layer again.
New data added, currently not synced.
1. All layers left at default display - everything appears on map as expected.
2.

**Comment by Timothy-D** [comment]
there have been cases in the past where clients have reported point features on the map getting duplicated, without any apparent pattern to it. Could do with identifying how frequent/severe this is; I don't know whether what you're seeing is a new bug or this previous intermittent one - or somewhere between the two..

**Comment by KathrynSteemson** [comment]
I think it is likely a previous intermittent bug, as everything seems fine again after another restart and can't replicate problem again.

**Comment by am-esdm** [comment]
**Device:** Samsung Galaxy Tab A
**OS Version:** Android v5.1.1
**App Version:** v4.4.2
**Sync Account:** xgWCP
**Status:** Pass
**Details:**
Tested the general functionality of this new feature using the existing 3 sub-layer Furniture configuration on this sync account ('A to B', 'C to O', 'S'), all seemed ok

**Comment by am-esdm** [comment]
**Device:** Samsung Galaxy Tab A
**OS Version:** Android v5.1.1
**App Version:** v4.4.2
**Sync Account:** xgStaffs
**Status:** Pass
**Details:**
Tested the general functionality of this new feature using the existing 3 sub-layer Furniture configuration on this sync account (also 'A to B', 'C to O', 'S', same as the xgWCP account above), all seemed ok

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.2
**Sync Account**: xgWCP
**Status**: Pass
**Details**: General test including adding new furniture items and synching - seems OK
