### ISSUE TITLE
Unable to plot items directly on top of routes or land parcels

### ISSUE THREAD

**Issue by Timothy-D** [exeGesIS-SDM/CAMS-Mobile#49]
Spotted in 3.4.9 - if you attempt to plot a furniture or issue item directly on  top of a route or land item, it doesn't accept this as the location for teh feature, but instead just shows the info pop-up for the route or land parcel.
Need to supress thE popup and take the screen tap as plotting the feature.

**Comment by LaineS** [comment]
Fixed in v4.3.10, you can now plot point features on top of other features

**Comment by am-esdm** [comment]
After testing on v4.3.10 on the older Samsung Galaxy Tab A device (on Android v5.1.1), this appears to now be working, will test later on the newer Samsung Galaxy Tab Active 2 device (on Android v8.??)

**Comment by am-esdm** [comment]
Tested in both v4.3.10 and v4.3.11 using the Samsung Galaxy Tab Active 2 device (on Android v8.1), seems to be working fine on that device now. Need to test on the older Samsung Galaxy Tab A device and pass to the wider CAMS Team for more varied testing before this can be signed off
