### ISSUE TITLE
Intermittent loss of Point features

### ISSUE THREAD

**Issue by Timothy-D** [exeGesIS-SDM/CAMS-Mobile#52]
Reported by Wales Coast Path:

> Icons fail to load in CAMS Mobile,   leading to duplicate entry being created by surveyor
> This happened twice on 13th of August 2019. 
> 1) Around Infra "Flint/475" and "Flint/96"
> 2) Around Issue 07006 where a pre-existing Unresolved Issue (01839) was there but not visible until I created the new Issue.

I have been able to replicate this here, but not in a consistent manner: it is **not** the case that there are particular records that do not draw until a new feature is plotted near them. Rather, it seems to be when you pan the map sometimes the redraw may not complete properly and some seemingly random features may not be shown - when you then pan the map again, those same features may appear.

I was testing this in the dev WCP dataset.

Given that these are point features, I don't think this is the same as #25. During investigation, I was using online background mapping and noticed on occasion that some of the background map tiles didn't draw, but the same one would after panning away and panning back. I wonder if this is some sort of timeout or similar in the map drawing component?

**Comment by LaineS** [comment]
Is this still a problem?

**Comment by am-esdm** [comment]
Yes and during testing of CAMS Mobile v4.3.12 I have been able to reproduce this a bit more reliably. This can be replicated by:

1. Sync to the 'xgeastsus' CAMS Mobile config account (ESDM test copy of the East Sussex client setup)
2. Log out of the app and back in with the default login, to make sure you are logged in with the correct mobile user for this API and sync account
3. Set the app to use online mapping
4. The map will default to start the map view at the town of Lewes in East Sussex
5. Without changing the map zoom scale level, pan the map slightly to the South, to centre the screen roughly on the village of 'Rodmell'
6. Press the zoom in button twice to view the map zoom scale level where the furniture and issue records are first displayed
7. Navigating from a start point of the centre of the Rodmell village, navigate South West by a short distance, to reach the Route Link record 'ROD/14/1' (status = Footpath, displaying in pink)
8. Making sure you are viewing the map at the first zoom level at which furniture and issue records display, working from the North-East end of the Link down to the South-West end of the Link, pan the map gradually towards the South-West, so that eventually the whole of the line Furniture record 'ROD/118' is displaying on screen in the top right of the screen, with part of the Route Link record 'ROD/14/1' displaying onwards towards the South West - at this point as a result of this bug you won't see any further furniture or issue records displaying on the rest of the visible on-screen part of the Link 'ROD/14/1', towards the South West
9. Now pan the map slightly so that only the North-West-most vertex end point of the line Furniture record 'ROD/118' is displaying on screen in the top right of the map screen, and the rest of its line feature is off-screen - at this point every time I've done this, the remaining Furniture and Issue line and point features on the Route Link record 'ROD/14/1' suddenly display along the Link towards the South-West, which should have been visible and selectable the whole time

**Comment by Timothy-D** [comment]
**Replicated**, but I think there is more to this
Working in the same location described above, this is panning north-east along link ROD/14/1:
![screenshot3](https://user-images.githubusercontent.com/25226464/82689067-d0590380-9c51-11ea-9b78-d0ca90ed5114.png)
Now you see them

![screenshot4](https://user-images.githubusercontent.com/25226464/82689091-db139880-9c51-11ea-9cf4-6d0c36b993fc.png)
Now you don't

Operating at one zoom level less, I also noticed that route lines were not displaying consistently - note this is a different issue to #25 as these are not the long, thin features:
![screenshot1](https://user-images.githubusercontent.com/25226464/82689463-69881a00-9c52-11ea-9ad3-eeeadbf0d2f6.png)
Now you see them

![screenshot2](https://user-images.githubusercontent.com/25226464/82689486-7278eb80-9c52-11ea-9819-eb7a6d312abc.png)
Now you don't

**Comment by am-esdm** [comment]
Tab A device, Android v5.1.1: Another example that particularly highlights the loss of Route line features is on the 'xgWCP' sync account, and simply navigating along the coast from Bangor to Llanfairfechan, where a reasonable number of lines disappear and reappear as you pan the map along

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.0
**Status**: Informational
**Details**:
Confirming that in the East Sussex dataset, this is replicable using both online and offline background mapping.

**Comment by Timothy-D** [comment]
Attempt to summarise this, as this now seems to be quite urgent...

1. This affects both Point and Line features. Haven't seen it affecting polygons, but we have fewer of those.
2. This seems to be happening more frequently in v4.3.12 and later than in previous builds.
3. This is not restricted to a single dataset; although it does seem more prominent in the East Sussex dataset, it has also been observed in the WCP and Central Beds datasets.
4. It is consistently replicable (see examples above), which did not seem the case previously. This may indicate that the issue has got worse in the newer version of the app, or that there are multiple causes of the same symptoms, some of which are newer.
5. It has been observed when using both online and offline background maps
6. On some occasions, features do not redraw on panning the map
7. On some occasions, features do not redraw on changing the visibility of other layers
8. It has been observed on different devices, suggesting this is not directly related to the version of android.

**Comment by LaineS** [comment]
I think this should be fixed now. A very odd bug, sometimes SQLite was querying the DB and reading any negative numbers as a string. But only doing this sometimes, so it wasn't finding some features...sometimes. Very odd. 

I found that by casting the data to a decimal then this behaviour vanished. So, hopefully fixed. I managed to replicate the bug 100% using eastsussex data and it is gone from that test scenario at least.

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.1
**Status**: Information
**Details**: Tested with xgWCP dataset. Did not notice any furniture items disappearing between Bangor & Llanfairfechan. Haven't noticed this with issue with Central Beds or xgDev datasets either.
Unable to test with East Sussex as I can't sync that dataset to the tablet (see #86)

**Comment by am-esdm** [comment]
**Device:** Samsung Galaxy Tab A
**OS Version:** Android v5.1.1
**App Version:** v4.4.1
**CAMS Mobile sync account:** xgWCP
**Details:** Didn't see any records disappearing between Bangor & Llanfairfechan (i.e. comparing to the documented scenario above). Further testing to follow as this is an important problem and may arise in other areas

**Comment by KathrynSteemson** [comment]
Device: Samsung Galaxy Tab A
OS Version: Android v5.1.1
App Version: v4.4.1
CAMS Mobile sync account: xgDev
Details: Problem with viewing of issues, not had any problem with furniture. Fully closing Mobile is not resolving issue. Only way I can get point issues to reappear is by toggling layer control.
Hard reset of device: New point issues added but not synced not displaying on the map. Line issues added present. Switch off furniture layer and issue points now appear (no changes made to issue layer display settings). Existing point issues unaffected, can only get new items to display if furniture layer is switched off. Config file updated to remove new furniture settings. Problem still present. Have not been able to test what happens to issues when they have been excepted into CAMS, suspect they will display correctely.

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.1
**Sync Account**: xgDev
**Status**: Informational
**Details**: Confirming that when newly created issues are synchronised up form the device, processed to CAMS and synchronised back down to the app, they then appear on the map.

**Comment by LaineS** [comment]
Ready to test in v4.4.2

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.2
**Sync Account**: xgEastSus
**Status**: Partial
**Details**:  
Tested original issue:

> 1. Sync to the 'xgeastsus' CAMS Mobile config account (ESDM test copy of the East Sussex client setup)
> 2. Log out of the app and back in with the default login, to make sure you are logged in with the correct mobile user for this API and sync account
> 1. Set the app to use online mapping
> 2. The map will default to start the map view at the town of Lewes in East Sussex
> 3. Without changing the map zoom scale level, pan the map slightly to the South, to centre the screen roughly on the village of 'Rodmell'
> 4. Press the zoom in button twice to view the map zoom scale level where the furniture and issue records are first displayed
> 5. Navigating from a start point of the centre of the Rodmell village, navigate South West by a short distance, to reach the Route Link record 'ROD/14/1' (status = Footpath, displaying in pink)
> 6. Making sure you are viewing the map at the first zoom level at which furniture and issue records display, working from the North-East end of the Link down to the South-West end of the Link, pan the map gradually towards the South-West, so that eventually the whole of the line Furniture record 'ROD/118' is displaying on screen in the top right of the screen, with part of the Route Link record 'ROD/14/1' displaying onwards towards the South West - at this point as a result of this bug you won't see any further furniture or issue records displaying on the rest of the visible on-screen part of the Link 'ROD/14/1', towards the South West
> 7. Now pan the map slightly so that only the North-West-most vertex end point of the line Furniture record 'ROD/118' is displaying on screen in the top right of the map screen, and the rest of its line feature is off-screen - at this point every time I've done this, the remaining Furniture and Issue line and point features on the Route Link record 'ROD/14/1' suddenly display along the Link towards the South-West, which should have been visible and selectable the whole time

Unable to replicate, so this seems fixed. Further testing needed on other problems noted above as this is a big issue.

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.2
**Sync Account**: xgeastsus
**Status**: Partial Pass
**Details**:

Tested this issue:

> 1. Go to map. Ensure Furniture layer (there is only the one configured) is turned on in the layer Control
> 2. Zoom in until furniture & issues are visible
> 3. Select a link and add a new issue
> 4. Save issue and return to the map. The new issue will not be displayed, but previous synced issues will

Unable to replicate. Looks OK but need to test in other datasets

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.2
**Sync Account**: xgDev
**Status**: Information
**Details**:
Revisited issue described above where
> an existing (synchronised) issue was not displaying, but the label was

On investigation, the cause of this was that the geometry was multipoint. Do we consider it acceptable to be unable to display multipoint features?

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.2
**Sync Account**: xgeastsus
**Status**: Partial Pass
**Details**:

Tested this issue:

> 1. Go to map. Ensure Furniture layer (there is only the one configured) is turned on in the layer Control
> 2. Zoom in until furniture & issues are visible
> 3. Select a link and add a new issue
> 4. Save issue and return to the map. The new issue will not be displayed, but previous synced issues will

Unable to replicate. Looks OK

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.2
**Sync Account**: Central Beds
**Status**: Pass
**Details**:  
Tested issue with adding new issues, with various combinations of furniture sub-layers visible. New issues always displayed on the map - seems OK
