### ISSUE TITLE
GPS marker z-position

### ISSUE THREAD

**Issue by Timothy-D** [exeGesIS-SDM/CAMS-Mobile#53]
Reported by Jon during the Kenfig survey. If you have a cluttered map then the GPS marker appears behind the furniture, issues routes etc and can be difficult to see.
I don't know if this relates to the changes made to fix #3 - but we need to make sure that it doesn't end up obscuring the business data or making it difficult to select them.

**Comment by Timothy-D** [comment]
Tested in v4.4.7 on Active 3 tablet - see screenshot below: it's not clear where the location marker is as it is obscured by other items:
![WhereIsGps](https://user-images.githubusercontent.com/25226464/124939283-e44ff800-e000-11eb-8a11-a6ecbb72b30c.png)

Need to make sure users can see the marker but it doesn't interfere with trying to select other map features.

**Comment by LaineS** [comment]
Marker is now shown on top of the other layers and still allows you to select anything underneath them

**Comment by Timothy-D** [comment]
Tested on emulator - seems to be an improvement, but of course this is heavily influenced by the map scale. Needs testing on true device.

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 3
**OS Version**: Android 10
**App Version**: 4.5.1
**Sync Account**: xgdev
**Status**: Mixed
**Details**: Appears on top of other layers, but is covered by labels (see below). Is it the case that labels are always on top and we cannot do anything about this? Otherwise OK.

![image](https://user-images.githubusercontent.com/25226464/133814506-d7303d2c-14e2-4a52-86ca-f3becba3440d.png)

**Comment by LaineS** [comment]
Yeah labels are always on top, not sure if/how we could change that

**Comment by Timothy-D** [comment]
As labels can be turned off separately under the layer control,  and this looks like it might be difficult, I'm happy to leave this one as it is.
