### ISSUE TITLE
UDF date values - format from CAMS Web/API not compatible with mobile

### ISSUE THREAD

**Issue by LaineS** [exeGesIS-SDM/CAMS-Mobile#59]
3-letter text month format e.g. 26 Mar 2019, as opposed to 26/03/2019, 26-03-2019, 03/26/2019 or any other arrangement).

The result of this problem is that the current date UDF values from the central SQL Server CAMS database are showing as NaN/NaN/0NaN on Mobile, presumably as Mobile isn't expecting the same date format - I thought this same problem was initially resolved in CAMS Mobile v4.3.9, but of course that version had the problem with the date and month values swapping around as described above.

So if you enter a new UDF date value in CAMS Mobile, this displays in Mobile ok, but syncs back to the database in the format 05/09/2019, which CAMS Desktop can actually handle and displays as 05 Sep 2019 but this isn't the desired format, or consistent with the other values' format in the database, and I believe may have accessibility standards problems for CAMS Web

Furthermore, if you enter any new records in Desktop with a date UDF value, or have existing records from the database with a date UDF value, after syncing back to Mobile these will display as NaN/NaN/0NaN. If you then edit one of these records with this NaN/NaN/0NaN value, e.g. edit a different field so that the record needs to be synced back, then sync it back to Desktop and import the update, the existing UDF date value gets wiped and replaced with a database value of '01/01/1901', displaying in CAMS Desktop as '01 Jan 1901'

LS: Please can you therefore apply the following format to the date UDFs in CAMS Mobile: DD MMM YYYY (i.e. with spaces in between and a 3-letter text month format e.g. 26 Mar 2019). Thanks

**Comment by am-esdm** [comment]
Tested in v4.3.11 using the Samsung Galaxy Tab Active 2 device (on Android v8.1), seems to be working fine on that device from what I've seen so far from limited testing in communication with CAMS Desktop. Need to test with records related to CAMS Web too and with a few varied date-related processes. Also need to test on the older Samsung Galaxy Tab A device and pass to the wider CAMS Team for more varied testing before this can be signed off

**Comment by LaineS** [comment]
More testing needed by Timothy/Ali

**Comment by am-esdm** [comment]
I completed more detailed testing on this a while back and it was all fine, but the CAMS Web interaction element is still untested and this is an outstanding task that was assigned to RC/DB a while back, I've just emailed RC again to remind him, then if the CAMS Web interaction is all fine we will be able to close this issue
