### ISSUE TITLE
Compatibility with google play store

### ISSUE THREAD

**Issue by Timothy-D** [exeGesIS-SDM/CAMS-Mobile#66]
Hampshire have paid for CAMS Mobile to be available on the play store.

In a previous test by TD & RG, it was found incompatible for 2 reasons:
1.	The package name com.exegesis.cams.mobile is already in use by another app (we don’t know what) so we need a new package name before it can be accepted.
2.	They won’t allow applications targeted at the API version 27 as it’s “too old” – apps have to be targeted to at least version 28

**Comment by LaineS** [comment]
Hi Timothy, can you take a look at the Google Play Store icon spec? We need these icons for the app store entry

https://developer.android.com/google-play/resources/icon-design-specifications

**Comment by am-esdm** [comment]
Getting a message upon loading the app that was installed via the Play Store Internal Testing area (accessed via web page link from LS): "LICENSE VALIDATION FAILURE: uk.co.exegesis.cams.mobile" - this temporarily pops up on the login page of the app, then disappears (i.e. seems to be a message displayed via Android)

**Comment by am-esdm** [comment]
Other than the license message mentioned above, from some basic testing I've completed today the app seems fine so far after this Google Play Internal Testing install. Obviously I haven't done exhaustive testing as I understand this isn't the best time for that, but the key functions seem to be ok from initial impressions and I didn't hit any obvious new problems

**Comment by Timothy-D** [comment]
Unable to test
Followed link to https://play.google.com/apps/internaltest/4698284635705449975 on the tab active (android 9), logged in and just got the page below - no change for several hours and no sign of any instructions or help from the play screen on what to do. Makes no difference whether there is or is not a CAMS Mobile previously installed.

![screenshot](https://user-images.githubusercontent.com/25226464/82678134-fd50ea80-9c40-11ea-876a-3243ea3665cd.png)

I would have thought there would just be a download link.

Guess this is just further evidence of the inadequacy and all-round lousiness of the google play store

**Comment by am-esdm** [comment]
Hi Timothy, I used the 'download it on Google Play' option, and then had to re-login to the Google Play Store before that would work, to make sure I was logged into the Google Play Store using the same email address as the link that LS sent the invite to (initially the device was only logged into the Google Play Store using a generic CAMS Team email address so the two bits weren't linking up). Can't remember exactly at which point, but at one point in the process I also found a useful workaround was to copy the link address for one of the links and access the url via a web browser instead rather than the Play Store, in case access via the Play Store isn't playing ball. Not the most straight-forward process, but one you can dig through by messing around a bit with it

**Comment by Timothy-D** [comment]
As suspected, further evidence of the inadequacy and all-round lousiness of the google play store.

Eventually got the app installed from the play store, on Samsung Tab Active 2 (android 9)
Crashes almost immediately on start up, unable to test.
No error messages or any useful feedback

These are the same symptoms seen with version 4.3.14, but I have confirmed this is v 4.3.13

Version 4.3.11 on the same tablet is stable, and I can log in and sync data

**Comment by am-esdm** [comment]
Ok well as my previous more successful testing was on a Samsung Galaxy Tab A (the older supported model) with Android v5.1.1, perhaps that suggests the difference relates to the Android version?

**Comment by Timothy-D** [comment]
The android version is certainly a possible if not probable factor.

However, this would be a bit surprising as the play store requires apps to be targeted at API level 28 - this seems to correspond to android 9. As my tablet is running android 9, this should be the version it's targetted at. If anything I would have expected it to work on 9 but not on 5.
Perhaps it's one of the components that we're using that has caused in incompatibility? although older versions of the app work on android 9.

Unless of course "targetted at" is google-speak for "doesn't work on" 😉

**Comment by am-esdm** [comment]
> Hi Timothy, can you take a look at the Google Play Store icon spec? We need these icons for the app store entry
> 
> https://developer.android.com/google-play/resources/icon-design-specifications

@Timothy-D how are you doing with this bit? thanks

**Comment by Timothy-D** [comment]
Here is an icon that matches the guidelines - reminds me of Win 3.1 icon rules, only with fewer options.
![CamsMobile4LogoForStore](https://user-images.githubusercontent.com/25226464/83031571-a1b1a300-a02c-11ea-8050-d01502f35dda.png)

I think you should be able to get the file from here

**Comment by am-esdm** [comment]
Thanks - from a brief discussion with LS earlier, apparently there are a few other entries we may need to fill in for the general play store page for the app - not a huge amount, just a couple of summary/description items, probably of a couple of sentences. @LaineS would you mind posting the URL for that page you showed me earlier, so TD can provide the relevant items/text? Thanks

**Comment by am-esdm** [comment]
For reference for everyone too, LS confirmed that in v4.4.0 he's switched the app back to using a package name of 'com.exegesis.cams.mobile' rather than 'uk.co.exegesis.cams.mobile', to allow the Geolocation plugin to work, worth considering whether this will work with the Google Play Store given the previous issue around the 'com.exegesis.cams.mobile' package name clash. Also worth mentioning with reference to https://github.com/exeGesIS-SDM/CAMS-Mobile/issues/83 in case of any overlap

**Comment by LaineS** [comment]
@Timothy-D Can you log into the Play store and take a look at the store entry? You'' probably need to change text, icons, graphics, etc. Let me know and I can show you around if it helps

**Comment by Timothy-D** [comment]
I've had a quick look at the entry through the play store app on the tablet logged in with my account. It looks like it needs:

1. Updated screenshots
2. Expanded descriptive text
3. Using the new icon shown above.

Are the login details for the managment/admin account in keepass? if so, which file?

**Comment by Timothy-D** [comment]
@LaineS - further to our discussion earlier, I can sign into the play store with my ...@gmail.com account, following the link you sent, but I just get to the account creation screen, which among other things is wanting a payment of $25:
![image](https://user-images.githubusercontent.com/25226464/83542568-0c625300-a4f3-11ea-9af7-f47861020b6b.png)

**Comment by Timothy-D** [comment]
@LaineS please advise re account to use - I think this all has to be done from one central account (that was what RG suggested) but I need to know details of this.

**Comment by LaineS** [comment]
You should have an invitation from Google a few weeks ago:

![image](https://user-images.githubusercontent.com/6085799/84007431-51114280-a968-11ea-98b4-7216d03f14ba.png)

**Comment by LaineS** [comment]
Should be ok now

![image](https://user-images.githubusercontent.com/6085799/84007508-730ac500-a968-11ea-8b15-db92ae3c732a.png)

**Comment by Timothy-D** [comment]
worked on play store entry for new 4.4.3 version. App is uk.co.esdm.cams.mobile; the older uk.co.exegesis.cams.mobile still seems to be there but I can't see a way to remove it.
Tried to make a test release of 4.4.3 but this seems to be stuck somewhere in the play store - certainly I can't see it through the play store app.

**Comment by Timothy-D** [comment]
App is now available on Play store via the URL https://play.google.com/apps/internaltest/4701032639960443648 - note this is only open to the CAMS Test Team. I have managed to access this on my tablet (Tab Active 2, android 9) with my account, but when I tried to install it just stuck on an endless twirler.

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.3
**Status**: Fail
**Details**:
CAMS mobile app does not seem to be available through the Play Store app (even logged in with my account) and have to access via a browser and the URL https://play.google.com/apps/internaltest/4701032639960443648 - this gives an install link but as above when I try to install it just sits on a twirler - no information about what it is trying to do and no messages. 
Normally Cams Mobile installs in < 1 minute, this has been sitting on the screen below for10 minutes and getting nowhere, the twirler just goes round and round, changing colour, but nothing helpful happens.
![play](https://user-images.githubusercontent.com/25226464/87139051-46afd480-c297-11ea-92b4-e24bfd082bb5.png)

I am accessing this using Firefox browser, and have checked under Settings that installing apps from Firefox is allowed - it is - so don't know what the issue is here. However, I don't know if it is anything that we will be able to do anything about, if this is a play store problem.

I think what is needed is for others to try installing the app via this method: @am-esdm and @KathrynSteemson should have permission to the link.

**Comment by Timothy-D** [comment]
Update: this has been running for over 2 hours now an still no progress

**Comment by LaineS** [comment]
v.4.4.4

Uploaded to Google Play and seems to be working ok
https://play.google.com/apps/internaltest/4701032639960443648

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.4
**Sync Account**: N/A
**Status**: Fail
**Details**: Behaviour as before
Version number is not shown on the play store screen, but following the link https://play.google.com/apps/internaltest/4701032639960443648 it shows the app updated date as 14 July 2020 so this looks like the right version.
When I click the install button it just sits on the multi-coloured timing twirler - has been on that screen for over an hour

Needs testing on other devices with other google accounts

**Comment by KathrynSteemson** [comment]
Device: Samsung Galaxy Tab Active
OS Version: Android 5.1
App Version: 4.4.4
Sync Account: esdmcams@gmail.com
Status: Pass
Details:
Successful install. Can see app downloading and then installing. CAMS mobile opens and can sync data etc.

**Comment by am-esdm** [comment]
> Device: Samsung Galaxy Tab Active
> OS Version: Android 5.1
> App Version: 4.4.4
> Sync Account: [esdmcams@gmail.com](mailto:esdmcams@gmail.com)
> Status: Pass
> Details:
> Successful install. Can see app downloading and then installing. CAMS mobile opens and can sync data etc.

Hi @KathrynSteemson - thanks, just for clarity please can you update your 'Device' listing in this entry? As I'm guessing it should read 'Samsung Galaxy Tab A'? Particularly key here as TD's testing on the Tab Active 2 device has had a different result (the OS version is also probably v5.1.1 here, but I'm sure we can work it out from v.5.1!). ta

**Comment by KathrynSteemson** [comment]
To clarify. 
Device: Samsung Tab A
OS Version: Android 5.1
App Version: 4.4.4
Sync Account: esdmcams@gmail.com
Status: Pass

**Comment by am-esdm** [comment]
**Device:** Samsung Galaxy Tab A
**OS Version:** Android v5.1.1
**App Version:** v4.4.4
**Sync Account:** N/A
**Status:** Pass
**Details:**

Downloaded from https://play.google.com/apps/internaltest/4701032639960443648 - had to use the link within the following process to download the app from the Play Store (the internal testing area).

Carried out some basic testing processes and it all seemed fine:

- Installed app
- Opened app and logged into default setup
- Synced xgWCP config
- Logged out and back in to the xgWCP API/setup
- Synced survey data
- Used map navigation and layer control functions
- Opened record forms for Route, Land, Furniture and Issues
- Opened camera function and took a photo
- Tried the 'move' map feature tool
- Checked assigned tasks ('tester' user) and viewed an assigned issue task on the map
- Used online and offline mapping - the latter verified the app could read from the external micro-SD card
- Basic check of Sync Status screen and System messages screen, seemed ok
- Currently syncing photos, so far the sync process has synced all metadata records ok and the photo sync is underway

**Comment by am-esdm** [comment]
**Device:** Samsung Galaxy Tab A
**OS Version:** Android v5.1.1
**App Version:** v4.4.4
**Sync Account:** xgWCP
**Status:** Pass
**Details:**

Quick update on my last entry: Photo sync finished ok and photos are displaying ok on a handful of records that I've checked

**Comment by LaineS** [comment]
Test on the Samsung Galaxy Tab 2 and the account and app works ok (installed, logged in and sync data)

**Comment by LaineS** [comment]
You can use the link below for open beta testing (no login required). This is the final stage before live release:
https://play.google.com/apps/testing/uk.co.esdm.cams.mobile

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: ?
**Sync Account**: N/A
**Status**: Fail
**Details**: Uninstalled CAMS Mobile. Went to https://play.google.com/apps/testing/uk.co.esdm.cams.mobile and joined testing programme. Followed link to play store where it says "This app is incompatible with your device" - well that is a blatant lie because I've been using it on this device previously when I installed it properly. I think this is a problem with the google play store.

**Comment by Timothy-D** [comment]
Attempt to upload 4.4.7 to play store - rejected as now the minimum target API level is 29 (android 10)
