### ISSUE TITLE
Can't view Issue on Furniture without saving a change to the Furniture condition

### ISSUE THREAD

**Issue by am-esdm** [exeGesIS-SDM/CAMS-Mobile#67]
At the moment (e.g. in v4.3.11 and v4.3.12 of CAMS Mobile) you cannot view the Issue form for an Issue on an item of Furniture without first entering a new Furniture 'current condition' value, which when you then click on the Issue record then gets saved as a new condition value. It would be good to be able to check the current Issue's details without having to enter the furniture condition - it would still require the validation on that Furniture condition field when you come back to the parent furniture record, i.e. when you save the parent Furniture it should still prompt for a value for the current condition

**Comment by am-esdm** [comment]
Need to be careful with this, in the scenario that a user does view the child Issue record and saves it, need to determine whether the interface should then simply return to the map (as I think it does now) having saved changes to the child Issue record without needing to save the parent Furniture record, or whether it should first return the interface to the parent Furniture record to give the user a chance to enter details and save those changes. Perhaps only do the latter if a Furniture Current Condition wasn't entered before viewing the child Issue record (and if the user chooses to cancel out of the Furniture form after returning from a saved child Issue form, ensure the child Issue changes are saved whilst any parent Furniture changes are discarded), and if a Furniture Current Condition was entered before viewing the child Issue record, then when the user saves the child Issue record, just return to the map and save changes to both the parent Furniture and child Issue. Timothy can you review this and confirm?

**Comment by Timothy-D** [comment]
A couple of potential scenarios here that have caused problems for users:
1. If the furniture item isn't saved when going to the issue, then any changes get lost, requiring you to save the furniture, then go back to it to view the issue.
2. If the furniture item is saved, then it requires all mandatory fields to be populated, forcing the user to enter a condition just to view the issue.

What can we do here?
- Is it possible for it to check for unsaved data before opening the issue form, and not try to save if there is no unsaved data?
- Can the furniture form be held in memory in the background while the issue form is open, then on closing the issue form (whether saving or not) return to the furniture form, not the map?

**Comment by LaineS** [comment]
I think this is fixed now. You should be able to open furniture features, then open issues on the feature without having to save the furniture first. Then you return to the furniture form to save/cancel as normal.

**Comment by Timothy-D** [comment]
Initial test shows can open the furniture item, then open the issue without being forced to save. Will need further testing:

Furniture (no change) > Issue (no change) > Cancel > Cancel _(should be no records to sync)_
Furniture (no change) > Issue (change) > Cancel > Cancel _(should be no records to sync)_
Furniture (no change) > Issue (change) > Save > Cancel _(should be 1 issue record to sync)_
Furniture (no change) > Issue (no change) > Cancel > Save _(should warn about missing condition)_
Furniture (change) > Issue (no change) > Cancel > Cancel  _(should be no records to sync)_
Furniture (change) > Issue (no change) > Save > Cancel  _(should be no records to sync)_
Furniture (change) > Issue (no change) > Cancel > Save  _(should be 1 furniture record to sync)_
Furniture (change) > Issue (change) > Cancel > Cancel  _(should be no records to sync)_
Furniture (change) > Issue (change) > Cancel > Save  _(should be 1 furniture record to sync)_
Furniture (change) > Issue (change) > Save > Cancel  _(should be 1 issue record to sync)_
Furniture (change) > Issue (change) > Save > Save  _(should be 1 furniture & 1 issue record to sync)_

**Comment by Timothy-D** [comment]
**Device**: Emulator
**OS Version**: Android 8
**App Version**: 4.5.0
**Sync Account**: xgdev
**Status**: Pass
**Details**:

1. Furniture (no change) > Issue (no change) > Cancel > Cancel _(should be no records to sync)_ **OK**
2. Furniture (no change) > Issue (change) > Cancel > Cancel _(should be no records to sync)_ **OK**
3. Furniture (no change) > Issue (change) > Save > Cancel _(should be 1 issue record to sync)_ **OK**
4. Furniture (no change) > Issue (no change) > Cancel > Save _(should warn about missing condition)_ **OK**
5. Furniture (change) > Issue (no change) > Cancel > Cancel  _(should be no records to sync)_ **OK**
6. Furniture (change) > Issue (no change) > Save > Cancel  _(should be no records to sync)_ **Shows 1 issue record to submit - OK**
7. Furniture (change) > Issue (no change) > Cancel > Save  _(should be 1 furniture record to sync)_  **OK**
8. Furniture (change) > Issue (change) > Cancel > Cancel  _(should be no records to sync)_ **OK**
9. Furniture (change) > Issue (change) > Cancel > Save  _(should be 1 furniture record to sync)_ **OK**
10. Furniture (change) > Issue (change) > Save > Cancel  _(should be 1 issue record to sync)_ **OK**
11. Furniture (change) > Issue (change) > Save > Save  _(should be 1 furniture & 1 issue record to sync)_  **OK**

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 3
**OS Version**: Android 10
**App Version**: 4.5.1
**Sync Account**: xgdev
**Status**: Pass
**Details**:

1. Furniture (no change) > Issue (no change) > Cancel > Cancel _(should be no records to sync)_ **OK**
2. Furniture (no change) > Issue (change) > Cancel > Cancel _(should be no records to sync)_ **OK**
3. Furniture (no change) > Issue (change) > Save > Cancel _(should be 1 issue record to sync)_ **OK**
4. Furniture (no change) > Issue (no change) > Cancel > Save _(should warn about missing condition)_ **OK**
5. Furniture (change) > Issue (no change) > Cancel > Cancel  _(should be no records to sync)_ **OK**
6. Furniture (change) > Issue (no change) > Save > Cancel  _(should be no records to sync)_ **Shows 1 issue record to submit - OK**
7. Furniture (change) > Issue (no change) > Cancel > Save  _(should be 1 furniture record to sync)_  **OK**
8. Furniture (change) > Issue (change) > Cancel > Cancel  _(should be no records to sync)_ **OK**
9. Furniture (change) > Issue (change) > Cancel > Save  _(should be 1 furniture record to sync)_ **OK**
10. Furniture (change) > Issue (change) > Save > Cancel  _(should be 1 issue record to sync)_ **OK**
11. Furniture (change) > Issue (change) > Save > Save  _(should be 1 furniture & 1 issue record to sync)_  **OK**
