### ISSUE TITLE
Problem with Issue Parent Code field when Issue recorded on parent Land record

### ISSUE THREAD

**Issue by am-esdm** [exeGesIS-SDM/CAMS-Mobile#70]
First identified during testing of CAMS Mobile v4.3.12: When you record a new Issue on a parent Land record in CAMS Mobile and sync the results back to CAMS Desktop, accept and process into CAMS Desktop, then sync the results back to CAMS Mobile, then open the Issue record in CAMS Mobile, it will correctly show the parent LandCode value in the Issue's ParentCode field, but then when you click that field (as you can with other records to choose a different parent record), it clears the existing value and doesn't display any LUT values for the parent LandCode so then you can't select anything or save any other changes to the Issue record

**Comment by Timothy-D** [comment]
Lock parent code fields so they are not editable.

**Comment by LaineS** [comment]
Fixed

* TD to update XSLT processing scripts
* LS made the issue and furniture parentCode and parentType fields readonly

**Comment by Timothy-D** [comment]
Check XSL & prep view

**Comment by Timothy-D** [comment]
**Device**: Emulator
**OS Version**: Android 8
**App Version**: 4.5.0
**Sync Account**: xgdev
**Status**: Pass
**Details**: Parent Type & Parent Code fields are not editable on issues

**Comment by Timothy-D** [comment]
**Device**: Samsung Tab Active 3
**OS Version**: Android 10
**App Version**: 4.5.1
**Sync Account**: xgdev
**Status**: Pass
**Details**: Parent Type & Parent Code fields are not editable on issues
