### ISSUE TITLE
Job fields require data entry validation

### ISSUE THREAD

**Issue by am-esdm** [exeGesIS-SDM/CAMS-Mobile#78]
First identified when testing CAMS Mobile v4.3.12: 'No. Units' and 'Repeat interval' fields (and probably Length and Width fields too) let you enter over-sized values (e.g. 99999999) that will then error when you try and process them into CAMS Desktop - these fields need data entry validation. Timothy can you advise what the required thresholds are for CAMS Desktop/the stored procedures/processing method?

**Comment by LaineS** [comment]
I'm not sure what forms these fields are on. Can you advise:

1. The forms and fields that need validation
2. What he validation is

**Comment by Timothy-D** [comment]
**Device**: Emulator
**OS Version**: Android 8
**App Version**: 4.5.0
**Sync Account**: xgDev
**Status**: pass

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 3
**OS Version**: Android 10
**App Version**: 4.5.1
**Sync Account**: xgdev
**Status**: Pass
**Details**:
