### ISSUE TITLE
Unexpected Issue sync submission in relation to viewing associated Job record

### ISSUE THREAD

**Issue by am-esdm** [exeGesIS-SDM/CAMS-Mobile#79]
**First identified when testing CAMS Mobile v4.3.12**

If you:
1. view an Issue record on CAMS Mobile that has an associated Job record (it can be a new or existing Job), don't make any changes to the Issue
2. then view the associated Job record within the Issue, don't make any changes to the Job, cancel back to view the parent Issue record again (selecting to discard any changes)
3. then cancel back to the map (selecting to discard any changes)
4. then check the CAMS Mobile app home screen, you'll see the number of records to sync has gone up by 1 even though you wouldn't have expected any new sync records as the user hasn't chosen to save any new data. 

If you carry out that sync, it appears that the parent Issue is the record that has been saved and synced back (presumably it is saved when you view the Job record), as you get an Issue record appearing in the CAMS Desktop Import Review screen - it can be either an 'Update' or 'Insert' (i.e. new record) Import Review record, depending on whether the Issue you were viewing in CAMS Mobile was an existing complete Issue record with an existing Issue code (resulting in an 'Update' Import Review entry)

If it was a new Issue that had been synced back to CAMS Desktop already but hadn't completed the Import and sync cycle back to CAMS Mobile so when a CAMS Mobile user subsequently opens that new incomplete Issue record, it is still a new Issue without an Issue code (resulting in an 'Insert' Import Review entry). 

The new sync record shouldn't exist either way, but the higher risk scenario is around the chance of the synced record appearing as an 'Insert' entry in the Import Review screen, as it would then create a second, duplicate Issue record when imported

**Comment by LaineS** [comment]
Should be fixed in v4.4.16
1. Open an existing issue, then tap the Jobs button (or tap the table with an existing job in)
2. The app will now warn the user and discard any issue changes before opening the job screen
3. On the job screen, cancel and return to the issue screen
4. Cancel from the issue screen and you should have no pending edits
5. If you save on any of the screens instead, you should get pending edits

**Comment by Timothy-D** [comment]
**Device**: Emulator
**OS Version**: Android 8
**App Version**: 4.5.0
**Sync Account**: xgdev
**Status**: Pass

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 3
**OS Version**: Android 10
**App Version**: 4.5.1
**Sync Account**: xg dev
**Status**: Pass
