### ISSUE TITLE
App homepage 'Help' button

### ISSUE THREAD

**Issue by am-esdm** [exeGesIS-SDM/CAMS-Mobile#81]

**Comment by am-esdm** [comment]
It doesn't currently appear to do anything (tested in CAMS Mobile v4.3.12 but from experience and conversation with the CAMS Team, this seems to have been the case in many recent CAMS Mobile releases), unless we just don't know how to configure this properly? There's this entry in the main CAMS Mobile CAMSMobileConfig_clientcode.js config file:

// Help URL

G_CAMS_MOBILE_HELP_URL = "https://camsdocumentation.esdm.co.uk/user-notes"; 

which seems to be a relevant URL when used via a laptop - it takes you to a login page first, but otherwise ok. Pressing 'help' in CAMS Mobile doesn't seem to do anything at all, it doesn't open a browser or anything. This should open a browser and take you to that URL. Timothy can you advise whether this should be some form of embedded browser within the app or whether it should simply open the URL in the tablet's default standalone web browser?

**Comment by Timothy-D** [comment]
This should just open the link in whatever is the default browser on the tablet

**Comment by Timothy-D** [comment]
Confirmed this does not work in 4.4.7: it clearly hasn't worked for a while and nobody has complained, so it probably isn't used. It cannot work without an internet connection anyway. Simplest solution may be just to remove the button completely. Please provide estimates for both options.

**Comment by LaineS** [comment]
Fixed and tested on Android 10

**Comment by Timothy-D** [comment]
**Device**: Emulator
**OS Version**: Android 8
**App Version**: 4.5.0
**Sync Account**: xgdev
**Status**: Pass
**Details**: Help button launches camsdocumentation web page in default browser. Need to test behaviour when no signal

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 3
**OS Version**: Android 10
**App Version**: 4.5.1
**Sync Account**: xgdev
**Status**: Pass
**Details**: Help button launches cams documentation web page in default browser. if no signal, opens browser app with "No network connection" page.
