### ISSUE TITLE
App no longer reads from removable SD card

### ISSUE THREAD

**Issue by Timothy-D** [exeGesIS-SDM/CAMS-Mobile#83]
Device = Samsung Galaxy Tab Active 2
OS = android 9

I have a removable SD card in the device, in this situation, CAMS Mobile should be using that removable card for storing its config files and map packs - this is how it's worked before. However, in v 4.4.0, it is downloading config files to the internal storage, and does not find the background map packs that are on the removable storage.

I think something like this happened before and it may be related to targetting the different android API

**Comment by am-esdm** [comment]
Device = Samsung Galaxy Tab A
OS = Android v5.1.1

I've also found the same with this device and Android combination

**Comment by am-esdm** [comment]
Just for clarity for everyone on the logistics for this: I've posted a Samsung Galaxy Tab Active 2 tablet (Android v9, posted earlier this week) to LS to allow him to replicate this, and from the latest communications I've seen it looked like GC was planning on dropping off a Samsung Galaxy Tab A (Android v5.1.1) tablet to LS' house too on Wednesday this week, so hopefully @LaineS will now be in a position to progress this

**Comment by LaineS** [comment]
Ready to test in v4.4.2

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.2
**Sync Account**: xgEastSus
**Status**: Pass
**Details**: Config downloaded and saved to removable card. Copied map pack files to the removable card, restarted CAMS Mobile and set to use offline maps. Background mapping available when panning, even when Wi-Fi was disabled.

**Note: There is a new location of folder on the card, on the Tab Active this was: /SD card/Android/data/_uk.co.esdm_.cams.mobile**
