### ISSUE TITLE
Map layer order changes when you change layer visibility

### ISSUE THREAD

**Issue by LaineS** [exeGesIS-SDM/CAMS-Mobile#84]

**Comment by LaineS** [comment]
The layers should stay in the correct order now when the app first loads and if you switch them on/off

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.1
**Status**: Pass
**Details**: Tested in Central Bedfordshire dataset. Toggling furniture, issue & route layers on and off does not change the order - OK.

**Comment by KathrynSteemson** [comment]
Device: Samsung Galaxy Tab A
OS Version: Android 5.1.1
App Version: 4.4.1
Status: Pass
Details: Tested in Staffs dataset. Toggling furniture, issue & route layers on and off does not change the order - OK.
