### ISSUE TITLE
Synced existing photos don't display on Issues

### ISSUE THREAD

**Issue by am-esdm** [exeGesIS-SDM/CAMS-Mobile#88]
Regarding the downloading of existing photos to the device (https://github.com/exeGesIS-SDM/CAMS-Mobile/issues/20), Issue records aren't currently showing the downloaded photos (they need to)

**Comment by Timothy-D** [comment]
**Further Information:**
Having downloaded photos to the tablet using the xgWCP dataset, I exported the database and checked the LibraryLink table using `select xgtype, count(id) from librarylink group by xgtype` - results as follows:

| xgKey | Count |
| --- | --- |
| infra | 7378 |
| maint | 4123 |
| route | 585 | 

So there are definitely Maint (Issue) images being downloaded.

Looking in the LibraryLink table, the Maint records as far as I can tell seem to be correctly populated (as the images are string-encoded, I can't tell if these are valid or not)

Here are some examples - these can all be found along the route running north-east from the Menai bridge, anticlockwise around Anglesey, close to the bridge:

| MaintCode | idThumb | Grid Ref | Type | Full image URL |
| --- | --- | --- | --- | --- |
|05553 | 27527 | SH55857201 | Missing Sign/FingerPost* | https://camsapidemo.esdm.co.uk/5.1/Reference/XGWCP/LLWS/LLFiles/27527/full_27527.jpg |
|05554 | 27528 | SH55847197 | Missing Sign/FingerPost* | https://camsapidemo.esdm.co.uk/5.1/Reference/XGWCP/LLWS/LLFiles/27528/full_27528.jpg |
|05556 | 27530 | SH55767177 | Missing Sign/FingerPost* | https://camsapidemo.esdm.co.uk/5.1/Reference/XGWCP/LLWS/LLFiles/27530/full_27530.jpg |
|05557 | 27531 | SH55757174 | Missing Sign/FingerPost* | https://camsapidemo.esdm.co.uk/5.1/Reference/XGWCP/LLWS/LLFiles/27531/full_27531.jpg |
|05558 | 27533 | SH55727163 | Missing Sign/WaymarkDisc* | https://camsapidemo.esdm.co.uk/5.1/Reference/XGWCP/LLWS/LLFiles/27533/full_27533.jpg |

All these URLS are valid and all the records have an entry in the [photo] field of the LibraryLink table. The above table was generated from the following SQL in the CAMS mobile database:
```
select M.maintcode, L.idThumb, M.gridref , M.TypeDescr, L.fullURL
from issue M join LibraryLink L on M.MaintCode = L.xgKey
where M.maintcode in ('05553', '05554', '05556', '05557', '05558')
order by maintcode
```

So it looks to me form this like the app is getting the right data, it just isn't using it properly to display the images on the issue (Maint) form.

**Comment by LaineS** [comment]
Version 4.4.4

Fixed bug so that photos for issues are now shown

**Comment by am-esdm** [comment]
**Device:** Samsung Galaxy Tab A
**OS Version:** Android v5.1.1
**App Version:** v4.4.4
**Sync Account:** xgWCP
**Status:** Pass - provisional
**Details:**
Initial test appears ok, photo sync process completed without any obvious problems, photos displaying on the few Issue records I opened

**Comment by am-esdm** [comment]
**Device:** Samsung Galaxy Tab A
**OS Version:** Android v5.1.1
**App Version:** v4.4.4
**Sync Account:** xgWCP
**Status:** Pass
**Details:**

Checked TD's original test set (05553, 05554, 05556, 05557, 05558) - a photo displayed for each of these

**Comment by am-esdm** [comment]
**Device:** Samsung Galaxy Tab A
**OS Version:** Android v5.1.1
**App Version:** v4.4.4
**Sync Account:** xgWCP
**Status:** Pass
**Details:**

General testing on this during the day hasn't highlighted any problems
