### ISSUE TITLE
Synced existing photos don't display on Land

### ISSUE THREAD

**Issue by am-esdm** [exeGesIS-SDM/CAMS-Mobile#89]
Regarding the downloading of existing photos to the device (https://github.com/exeGesIS-SDM/CAMS-Mobile/issues/20), Land records aren't currently showing the downloaded photos (they need to)

**Comment by Timothy-D** [comment]
**Further information**
Having downloaded photos to the tablet using the xgWCP dataset, I exported the database and checked the LibraryLink table using `select xgtype, count(id) from librarylink group by xgtype`
This showed there were no entries for Land records in the table, so I suspect this is simply a case of it not tryign to get teh Land photos.

**Comment by LaineS** [comment]
v4.4.4

Fixed, all land photos should be downloaded

**Comment by am-esdm** [comment]
**Device:** Samsung Galaxy Tab A
**OS Version:** Android v5.1.1
**App Version:** v4.4.4
**Sync Account:** xgWCP
**Status:** Pass - provisional
**Details:**
Initial test appears ok, photo sync process completed without any obvious problems, photos displaying on the couple of Land records I opened

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.4
**Sync Account**: xgWCP
**Status**: Pass - Provisional
**Details**: There are only a couple of land parcels in this dataset with photos, but photos displayed for both OK.

**Comment by KathrynSteemson** [comment]
Device: Samsung Galaxy Tab A
OS Version: Android v5.1.1
App Version: v4.4.4
Sync Account: xgWCP
Status: Pass - provisional
Details:
Photos are displaying on the limited number of records with land attached.

**Comment by am-esdm** [comment]
**Device:** Samsung Galaxy Tab A
**OS Version:** Android v5.1.1
**App Version:** v4.4.4
**Sync Account:** xgWCP
**Status:** Pass
**Details:**
Photos are displaying on new Land records I've added too

**Comment by am-esdm** [comment]
**Device:** Samsung Galaxy Tab A
**OS Version:** Android v5.1.1
**App Version:** v4.4.4
**Sync Account:** xgWCP
**Status:** Fail
**Details:**

If you just sync the Land data (currently 7 records), then sync the photos, the photos sync appears to complete ok and states a total of 4 photos downloaded. If you then look at the records, they show an image but it is just blank. Having then downloaded the CAMS Mobile database, the Land table shows all its 7 records ok, but the LibraryLink table, whilst showing all 4 record entries, doesn't have any values in the 'photo' field, i.e. the values are just {null}. The 'status' field value for all 4 records is 'GotMetadata'. The 'fullURL' values are all populated and are valid and the image can be viewed ok at each URL:

Land Code 00002, idThumb 42627
https://camsapidemo.esdm.co.uk/5.1/Reference/XGWCP/LLWS/LLFiles/42627/full_42627.png

Land Code 00003, idThumb 42618
https://camsapidemo.esdm.co.uk/5.1/Reference/XGWCP/LLWS/LLFiles/42618/full_42618.png

Land Code 00006, idThumb 42628
https://camsapidemo.esdm.co.uk/5.1/Reference/XGWCP/LLWS/LLFiles/42628/full_42628.png

Land Code 00007, idThumb 42636
https://camsapidemo.esdm.co.uk/5.1/Reference/XGWCP/LLWS/LLFiles/42636/full_42636.png

So it looks like it's just the last step of displaying the images which isn't quite right. But when I checked these same Land records before, when a full data sync for all entity types had been completed, all the images were displaying ok.

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.4
**Sync Account**: xgWCP
**Status**: Replication
**Details**:
Confirming the behaviour noted above:
_Pass 1_
1. Start from empty database
2. Sync Land = 7 records
3. Download photos = completes quickly, date updated but shows 0 photos. If you look at the land records, they show no photos (just the screen to add a new one).
4. Sync Routes = 4169 route records
5. Download photos = completes, timestamp updated, shows 591 photos. If you look at route or land records, photos now display.

_Pass 2_
1. Start from empty database
2. Sync Routes = 4169 route records
3. Download photos = completes OK, date/time updated, shows 587 photos. Images seem to display on routes where they should.
2. Sync Land = 7 land records
5. Download photos = completes, timestamp updated, shows 591 photos. If you look at a land record, the photo does not display, as per the image below. Photos on route records seem to show OK
6. Sync Issues = 4463 records
7. Download photos =  timestamp updated, shows 4917 photos. Photos now seem to show OK for route, land & issue records

_Pass 3_
1. Start from empty database
2. Sync Routes = 4169 route records
2. Sync Land = 7 land records
3. Download photos = completes OK, date/time updated, shows 587 photos. Images seem to display on both routes & Land where they should.

![MissingPhoto](https://user-images.githubusercontent.com/25226464/87688967-8dae3600-c77f-11ea-9230-a852b4d3a71c.png)

**Comment by LaineS** [comment]
Fixed in v4.4.5

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.5
**Sync Account**: xgWCP
**Status**: Pass
**Details**: Tested previous behaviour
_Pass 1_
1. Start from empty database
2. Sync Land = 7 records
3. Download photos = completes quickly, date updated and shows 4 photos. If you look at the land records, photos display correctly.
4. Sync Routes = 4169 route records
5. Download photos = completes, timestamp updated, shows 591 photos. If you look at route or land records, photos now display.

_Pass 2_
1. Start from empty database
2. Sync Routes = 4169 route records
3. Download photos = completes OK, date/time updated, shows 587 photos. Images seem to display on routes where they should.
4. Sync Land = 7 land records
5. Download photos = completes, timestamp updated, shows 591 photos. If you look at a land record, the photo displays OK
6. Sync Issues = 4463 records
7. Download photos = timestamp updated, shows 4917 photos. Photos now seem to show OK for route, land & issue records

_Pass 3_
1. Start from empty database
2. Sync Routes = 4169 route records
3. Sync Land = 7 land records
4. Download photos = completes OK, date/time updated, shows 587 photos. Images seem to display on both routes & Land where they should.
