### ISSUE TITLE
Photos not always synced for every record

### ISSUE THREAD

**Issue by am-esdm** [exeGesIS-SDM/CAMS-Mobile#90]
As mentioned in @Timothy-D 's feedback for https://github.com/exeGesIS-SDM/CAMS-Mobile/issues/20, photos aren't always synced for every record - TD gave an example in that feedback for Furniture records, but once that has been checked, the same method needs to be checked/applied as needed for each entity type (Route, Issues, Furniture, Land). If @LaineS considers the lack of photo in some cases to be a valid result, the reason why needs to be explained please

**Comment by Timothy-D** [comment]
For clarity, here are some examples from the xgWCP dataset of furniture items and the display (or not) of photos:

- Isle/2164 = shows photo
- Isle/2165 = shows photo
- Isle/2167 = no photo shown but one associated
- Isle/2169 = shows photo
- Isle/2170 = shows photo
- Isle/2171 = shows photo
- Isle/2772 = shows photo
- Isle/2773 = no photo shown but one associated

These are all around Beaumaris

Taking **Isle/2167** as an example:
1. No image shown in the app for this record
1. Connected to the LibraryLink Web service at https://camsapidemo.esdm.co.uk/5.1/Reference/XGWCP/LLWS/librarylinkws.asmx as used by CAMS Mobile.
2. Invoked method GetFileInfoByXGTypeAndXGKeyWithURLS with xgtype = 'infra', xgkey = 'Isle/2167', MaxNumberOfPhotos = 1. This returned valid data, including the URL for the image: https://camsapidemo.esdm.co.uk/5.1/Reference/XGWCP/LLWS/LLFiles/5398/full_5398.JPG - which is valid.
3. Exported CAMS Mobile database from the app and transferred to laptop.
4. select * from librarylink where xgkey = 'isle/2167' returns no rows
5. Does this suggest it is fialing at the metadata stage?

**Comment by LaineS** [comment]
Version 4.4.4

* Fixed bug so that photos for issues are now shown

**Comment by LaineS** [comment]
v4.4.4

Fixed, all photos should now be correctly downloaded

**Comment by am-esdm** [comment]
**Device:** Samsung Galaxy Tab A
**OS Version:** Android 5.1.1
**App Version:** v4.4.4
**Sync Account:** xgWCP
**Synced photos option:** Full
**Status:** Fail

Found the following example where the photo didn't download:

Furniture record 'Flint/65': linked in LibraryLink to idThumbs '9198', '22285', '35394' - the '9198' and '35394' ones are also listed in the 'vFilterFilesInDatabase' LibraryLink database view feeding the LLWS (the '9198' one appears there because it is associated with a different record (Issue 01825), otherwise as 35394 is higher it would filter 9198 from the view), and both of these idThumbs are returned by the LLWS call (using the GetFileInfoByXGTypeAndXGKeyWithURLS method) - the LLWS lists '35394' first and then '9198' - only the '35394' one is returned if you specify the requestedMaxNumFiles parameter as 1. The images are produced ok as well in their URLs:

https://camsapidemo.esdm.co.uk/5.1/Reference/XGWCP/LLWS/LLFiles/35394/full_35394.jpg

https://camsapidemo.esdm.co.uk/5.1/Reference/XGWCP/LLWS/LLFiles/9198/full_9198.JPG

The furniture record of interest here 'Flint/65' exists ok on the CAMS Mobile map:

![image](https://user-images.githubusercontent.com/33840701/87563307-f8e00580-c6b6-11ea-9297-fe75edaf2913.png)

Contextual location shot here:

![image](https://user-images.githubusercontent.com/33840701/87563363-072e2180-c6b7-11ea-870a-4fffd9b54722.png)

But no image has been downloaded for it - checked this in the app, plus manually in an export of the CAMS Mobile database, plus using this query against the CAMS Mobile database: select * from librarylink where xgKey = 'Flint/65'

The only other possibly relevant bit of context that I can see (which may not be relevant at all) is that 'Flint/65' 's other associated idThumb, '9198', is also associated with the Issue record 01825, which is a resolved Issue meaning the Issue wouldn't display on CAMS Mobile. I'm just wondering whether there is any overlap there with my feedback today (15th July 2020, 13:38) on the #20 GitHub task

**Comment by am-esdm** [comment]
> **Device:** Samsung Galaxy Tab A
> **OS Version:** Android 5.1.1
> **App Version:** v4.4.4
> **Sync Account:** xgWCP
> **Synced photos option:** Full
> **Status:** Fail
> 
> Found the following example where the photo didn't download:
> 
> Furniture record 'Flint/65': linked in LibraryLink to idThumbs '9198', '22285', '35394' - the '9198' and '35394' ones are also listed in the 'vFilterFilesInDatabase' LibraryLink database view feeding the LLWS (the '9198' one appears there because it is associated with a different record (Issue 01825), otherwise as 35394 is higher it would filter out 9198 from the view), and both of these idThumbs are returned by the LLWS call (using the GetFileInfoByXGTypeAndXGKeyWithURLS method) - the LLWS lists '35394' first and then '9198' - only the '35394' one is returned if you specify the requestedMaxNumFiles parameter as 1. The images are produced ok as well in their URLs:
> 
> https://camsapidemo.esdm.co.uk/5.1/Reference/XGWCP/LLWS/LLFiles/35394/full_35394.jpg
> 
> https://camsapidemo.esdm.co.uk/5.1/Reference/XGWCP/LLWS/LLFiles/9198/full_9198.JPG
> 
> The furniture record of interest here 'Flint/65' exists ok on the CAMS Mobile map:
> 
> ![image](https://user-images.githubusercontent.com/33840701/87563307-f8e00580-c6b6-11ea-9297-fe75edaf2913.png)
> 
> Contextual location shot here:
> 
> ![image](https://user-images.githubusercontent.com/33840701/87563363-072e2180-c6b7-11ea-870a-4fffd9b54722.png)
> 
> But no image has been downloaded for it - checked this in the app, plus manually in an export of the CAMS Mobile database, plus using this query against the CAMS Mobile database: select * from librarylink where xgKey = 'Flint/65'
> 
> The only other possibly relevant bit of context that I can see (which may not be relevant at all) is that 'Flint/65' 's other associated idThumb, '9198', is also associated with the Issue record 01825, which is a resolved Issue meaning the Issue wouldn't display on CAMS Mobile. I'm just wondering whether there is any overlap there with my feedback today (15th July 2020, 13:38) on the #20 GitHub task

Ok having re-run the sync this 'Flint/65' photo is now displaying! The outcome of that being that not all of the photos were synced the first time. The first photos sync returned 12846 photos. After syncing the second time, the total on CAMS Mobile was topped up to 13377 - so 531 extra photos. Encouragingly (and at the same time annoyingly in terms of my previous attempts to understand the 12846 total!) 13377 photos was the figure I arrived at when trying to calculate a total in SQL to validate the CAMS Mobile synced photos total against (though I'm not 100% certain of that validation figure yet as it's relatively complicated)

**Comment by am-esdm** [comment]
**Device:** Samsung Galaxy Tab A
**OS Version:** Android 5.1.1
**App Version:** v4.4.4
**Sync Account:** xgWCP
**Synced photos option:** Full
**Status:** Provisional pass

Tried clearing the data and syncing all photos again, and this time it synced all of the 13377 photos. The 'Flint/65' photo displayed. Haven't checked all of Timothy's previously highlighted individual records yet, but overall sync seems ok so far, not sure what happened the first time, maybe the full sync might sometimes need rerunning with a second smaller topup sync to make sure 100% of the photos come through

**Comment by am-esdm** [comment]
> For clarity, here are some examples from the xgWCP dataset of furniture items and the display (or not) of photos:
> 
> * Isle/2164 = shows photo
> * Isle/2165 = shows photo
> * Isle/2167 = no photo shown but one associated
> * Isle/2169 = shows photo
> * Isle/2170 = shows photo
> * Isle/2171 = shows photo
> * Isle/2772 = shows photo
> * Isle/2773 = no photo shown but one associated
> 
> These are all around Beaumaris
> 
> Taking **Isle/2167** as an example:
> 
> 1. No image shown in the app for this record
> 2. Connected to the LibraryLink Web service at https://camsapidemo.esdm.co.uk/5.1/Reference/XGWCP/LLWS/librarylinkws.asmx as used by CAMS Mobile.
> 3. Invoked method GetFileInfoByXGTypeAndXGKeyWithURLS with xgtype = 'infra', xgkey = 'Isle/2167', MaxNumberOfPhotos = 1. This returned valid data, including the URL for the image: https://camsapidemo.esdm.co.uk/5.1/Reference/XGWCP/LLWS/LLFiles/5398/full_5398.JPG - which is valid.
> 4. Exported CAMS Mobile database from the app and transferred to laptop.
> 5. select * from librarylink where xgkey = 'isle/2167' returns no rows
> 6. Does this suggest it is failing at the metadata stage?

**Device:** Samsung Galaxy Tab A
**OS Version:** Android 5.1.1
**App Version:** v4.4.4
**Sync Account:** xgWCP
**Synced photos option:** Full
**Status:** Provisional pass

Checked these records again, all showed photos except 'Isle/2773' which when checked in the LibraryLink database didn't have an associated image - not sure why this is different to TD's note above, maybe the data has changed since. All fine though on this basis
