### ISSUE TITLE
Create separate 'clear' button for photos

### ISSUE THREAD

**Issue by am-esdm** [exeGesIS-SDM/CAMS-Mobile#91]
A new 'clear photos' button needs to be created within the Sync Status window, I'd suggest underneath the existing 'clear survey data' button in that window (which has a recycle bin icon). Clicking the button should initially produce a similar user-warning message as the existing 'clear survey data' button, warning them that they are about to clear all photos and asking them if they really want to proceed, with an option to 'cancel' back (and do nothing) and an 'ok' button to proceed which should clear all photos from the app.

Other than the existing processes that remove new user-taken photos after they are synced back to CAMS Desktop, no photos should be removed by any other processes.

For information only:
In the existing (v4.4.3) app it isn't clear when photos are removed, and the only way I've found to remove them seems to be to uninstall and reinstall the app which obviously isn't ideal and won't be suitable for users. Also the existing v4.3.3 app seems to try and check for and sync photos for more records than you'd expect if you're in this scenario or similar:
1. You've already synced survey data and photos for all entity types
2. You clear the synced survey data, which doesn't seem to clear any photos
3. You sync just e.g. Routes survey data
4. You run the sync photos routine, which you'd expect just to sync photos for Routes (which it does as expected if you haven't ever synced photos before), but based on the number of metadata records it checks, it appears to be trying to sync photos for all entity types perhaps based on the Routes survey data synced plus all the existing photos for all entity types in the background which haven't been removed?

**Comment by LaineS** [comment]
v4.4.5

* Added a button to remove all LibraryLink photos

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.5
**Sync Account**: xgWCP
**Status**: Pass
**Details**: Clear button on sync status screen deletes photos but leaves main data

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.5
**Sync Account**: xgStaffs
**Status**: Fail
**Details**: The button does NOT get hidden when `G_SHOW_DOWNLOADBUTTON_FORLIBRARYLINK = false;` - this setting should hide the clear button

**Comment by am-esdm** [comment]
**Device:** Samsung Galaxy Tab A
**OS Version:** Android v5.1.1
**App Version:** v4.4.5
**Sync Account:** xgEastSus and xgDev
**Status:** Fail
**Details:**

Confirming the same behaviour as noted by TD above, for these sync accounts and this device/OS, panel not hidden as expected when config value set to false

**Comment by LaineS** [comment]
* TD to fix a bug found in the CAMS Config and re-test

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.5
**Sync Account**: xgEastSus
**Status**: Fail
**Details**: The button does NOT get hidden when `G_SHOW_DOWNLOADBUTTON_FORLIBRARYLINK = false;` - this setting should hide the clear button. Also observed the same on xgDev dataset

This is the xgEastSus config file: [CAMSMobileConfig_xgEastSus.js](https://github.com/exeGesIS-SDM/CAMS-Mobile/files/4987719/CAMSMobileConfig_xgEastSus.txt)

**Comment by LaineS** [comment]
Working in v4.4.6

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.6
**Sync Account**: xgEastSus / xgDev / xgWcp
**Status**: Pass
**Details**: Switched between config files, checked whether panel and button appear
- Synced xgEastSus config (turned off in config) - did not display
- Synced xgDev config (turned off in config) - did not display
- Synced xgWcp config (turned on in config) - displayed
- Synced xgDev config (turned off in config) - did not display

**Comment by am-esdm** [comment]
**Device:** Samsung Galaxy Tab A
**OS Version:** Android v5.1.1
**App Version:** 4.4.6
**Sync Account:** xgEastSus
**Status:** Pass
**Details:** Synced xgEastSus config, checked whether the clear photos button appeared, it didn't (as expected, as the 'G_SHOW_DOWNLOADBUTTON_FORLIBRARYLINK' config was set to false)
