### ISSUE TITLE
Change the photos sync process (in #20) to use a change-only sync basis

### ISSUE THREAD

**Issue by am-esdm** [exeGesIS-SDM/CAMS-Mobile#93]
Change the photos sync process (in https://github.com/exeGesIS-SDM/CAMS-Mobile/issues/20) to use a change-only sync basis, whereby the new process check all records for their latest photo provided from the LibraryLink Web Service and in the case where an existing photo has already been synced and an updated different photo is available, replaces the existing synced photo with the new one (without removing any user-taken new photos), and in the case where a record didn't have a photo, it gets the new photo. If a record already has a synced photo and the LibraryLink Web Service photo is still the same for that record, the photo download should be skipped for that record. If a record already has a synced photo and the LibraryLink Web Service no longer publishes any photo for that record, the existing synced photo for that record should be removed (without removing any user-taken new photos)

**Comment by LaineS** [comment]
v4.4.4

This service now
1. Get fresh metadata by querying the API each time you hit the 'get photos' button. This takes quite a while because the API is not meant for this sort of query and is quite slow. This process could be sped up 100x if we were to add an appropriate endpoint on the API

2. The metadata info is then saved to the CAMS mobile DB _after_ the query step above is finished for all records. THe idThumb and URL is recorded for each record

3. The app then downloads the image for each of the rows in the LibraryLink table. It saves the photos to the DB every 50 requests. 

4. If you hit the 'get photos' button again, it will still go through steps 1 and 2 as normal. But in step 3 it will only get photo's for records that do not already have a photo, records that might have failed when downloading a photo (and thus do not have a photo) or for records that have a different idThumb compared with the one already downloaded

**Comment by am-esdm** [comment]
Thanks Laine, please can you confirm whether this part of the specification has been completed:

"If a record already has a synced photo and the LibraryLink Web Service no longer publishes any photo for that record, the existing synced photo for that record should be removed (without removing any user-taken new photos)"

**Comment by am-esdm** [comment]
> Thanks Laine, please can you confirm whether this part of the specification has been completed:
> 
> "If a record already has a synced photo and the LibraryLink Web Service no longer publishes any photo for that record, the existing synced photo for that record should be removed (without removing any user-taken new photos)"

Just to note for everyone, this bit hasn't been included in v4.4.4, and it is intended that it will be included in the next .apk

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.4
**Sync Account**: xgWCP
**Status**: Inconclusive
**Details**: I know there is more work to be done on this issue. This are some comments at the current time.
- Regarding timing: yes, the metadata download is slow, but I don't see this as a huge problem. This is not something that users will be doing every day, most probably just once at the beginning of a survey season. However it is important that we can do a partial download so if it does fail part way through, it can be continued.
- Not sure how best to test this, but tried the following:
    - Synced issues (4463 records)
    - Downloaded photos (4324 photos)
    - Synced Routes (4169 records)
    - Downloaded Photos: Metadata counter ran to 8600, then photo download counter ran to 550 and the app reported complete. photo counter shows 4909 **- Is this discrepancy because the download counter only updates after every 50 records?**

**Comment by am-esdm** [comment]
**Device:** Samsung Galaxy Tab A
**OS Version:** Android v5.1.1
**App Version:** v4.4.4
**Sync Account:** xgWCP
**Status:** Provisional pass
**Details:**

Checked this for new photos for the following records that didn't have an existing photo - all worked fine - the new photo came through:

issue 05567
issue 05571
furniture isle/2007 (line)
furniture isle/2010
furniture isle/2101
route isle/4380/1
route gwyne/0390/1
land 00006

Checked this for new photos for the following records that had an existing older photo - all worked fine - the older photo was replaced with the newer one:

issue 05566
furniture isle/2100
route cered/0540/1
land 00002

Also checked a few other random records of each record entity type and they had retained their photos, i.e. the sync hadn't removed other photos (at least from these random spot checks) - all good.

The photo download bit of the photo sync process was also a lot quicker (for any sync after the initial full sync of all photos), so it appears the sync isn't carrying out redundant syncing of photos for records where there is no change in photo, as requested - all good.

The total number of photos shown as downloaded in the Sync Status screen's 'Library Link Photos' section also increased by the expected amount during these tests.

Consultant Testers (@Timothy-D , @KathrynSteemson ): One thing to remember which I initially forgot during this testing, is that if you link and new images to the CAMS records, you subsequently need to run the 'Import Files to Database' tool in LibraryLink Desktop to import them, to allow the LibraryLink Web Service (LLWS) to grab the 'full' (and if used, 'original') size image, which in turn allows CAMS Mobile to display the new image. If you don't do this, the LLWS just produces a blank 'original' image (not sure why it doesn't produce a 'full' image in this scenario, but that point is slightly redundant anyway) and CAMS Mobile just displays a blank image

**Comment by LaineS** [comment]
Outstanding: if a photo on LL has been removed, it also needs to be removed from the device

**Comment by LaineS** [comment]
* Added new CAMS Config setting: G_LIBRARYLINK_requestedMaxNumFiles=50;
* App iterates through all metadata and chooses the one with the highest idThumb

**Comment by am-esdm** [comment]
**Device:** Samsung Galaxy Tab A
**OS Version:** Android v5.1.1
**App Version:** v4.4.5
**Sync Account:** xgWCP
**Synced photos option:** Full
**Status:** Fail
**Details:**

Tested the removal of already downloaded/synced photos by excluding the following records from the LibraryLink database's 'vFilterFilesInDatabase' view which filters the LibraryLink Web Service (LLWS):

Land 00002
Route Gwyne/0390/1
Infra Gwyne/724
Maint 07390

All four of these records previously had a synced photo and the app had a full photos sync completed before I applied the above filtering.

After filtering these records out, I manually tested the LLWS's return for each of them at the LLWS webpage (using its GetFileInfoByXGTypeAndXGKeyWithURLS method) and no image/idThumb was returned for any of them.

I then resynced the photos on the app (I didn't clear them first, i.e. it was a change-only sync) and then re-checked the four records. All of them had had their downloaded photo image removed, but upon viewing the photo part of each of the records, they all seemed to show a blank image (i.e. just the same colour as the general background of that window, with the images carousel scroll marker below the 'blank' image) and a number ('1') decoration on the camera button within the photos window suggesting that there was 1 photo available in each record. The user-instruction text that normally displays in that window when no photo has been taken or downloaded was not visible. All of that perhaps suggests that whilst the image has been removed the metadata for the image hasn't? E.g. the record thinks it has an image but can't display any image as there isn't one?

This is an example screenshot of one of the affected records:

![image](https://user-images.githubusercontent.com/33840701/88323260-df276980-cd19-11ea-80d4-095a6b9aaa8f.png)

I also checked a reasonable number of other records of different data entity types and they all either still had their downloaded image, or displayed the default user-instruction text for a record with no photo taken/downloaded, as follows in this screenshot:

![image](https://user-images.githubusercontent.com/33840701/88323385-0ed67180-cd1a-11ea-8e36-a25a002bdc05.png)

Looks like the images metadata needs to be included in the removal process during the change-only photos sync?

(For reference, I returned the the vFilterFilesInDatabase view back to its default structure afterwards)

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.5
**Sync Account**: xgWCP
**Status**: Fail
**Details**: Testing on unlinking photos:
- Added 4 images to Route Isle/0340/1:
    - 5459 ("DSCF4811.JPG")
    - 5460 ("DSCF4812.JPG")
    - 28027 ("Infra_Isle-2209_1.jpg")
    - 28028 ("Infra_Isle-2209_2.jpg")
- Downloaded photos to device
- Isle/0340/1 Shows image 28028
- Unlinked image 28028
- Downloaded photos to device
- Isle/0340/1 Shows a blank image (see below)
- Deleted all photos
- Downloaded photos to device
- Isle/0340/1 Shows a blank image (see below)
- Deleted all photos
- Restarted app
- Downloaded photos to device
- Isle/0340/1 Shows a blank image (see below)
- Deleted all photos
- Deleted all data
- Synchronised Route & LUT data
- Downloaded photos to device
- Isle/0340/1 Shows a blank image (see below)

![MissingPhoto](https://user-images.githubusercontent.com/25226464/87688967-8dae3600-c77f-11ea-9230-a852b4d3a71c.png)

**Comment by LaineS** [comment]
* When calculating the max idThumb, do not count non-image types

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.6
**Sync Account**: xgWCP
**Status**: Pass
**Details**: Testing on unlinking photos:
- Added 4 images to Route Isle/0340/1:
    - 9115 ("DSCF5449.JPG")
    - 9119 ("DSCF5453.JPG")
    - 9584 ("DSCF5918.JPG")
    - 28028 ("Infra_Isle-2209_2.jpg")
- Confirmed all these images are returned by LLWS
- Downloaded photos to device
- Isle/0340/1 Shows image 28028
- Unlinked image 28028
- Downloaded photos to device
- Isle/0340/1 Shows image 9115
- Unlinked image 9115
- Downloaded photos to device
- Isle/0340/1 Shows image 9584
- Unlinked image 9584
- Isle/0340/1 Shows image 9119
- Unlinked image 9119
- Downloaded photos to device
- Isle/0340/1 shows no image
- Downloaded photos to device

This item is OK, further testing needed in other schenarios

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.6
**Sync Account**: xgWCP
**Status**: Fail
**Details**: Testing with missing photos:
- Added 2 images to Route Isle/0350/1:
    - 9115 ("DSCF5449.JPG") - served by LLWS
    - 9117 ("DSCF5451.JPG") - not served by LLWS: returned in metadata but 404 error returned from https://camsapidemo.esdm.co.uk/5.1/Reference/XGWCP/LLWS/LLFiles/9117/full_9117.JPG
- Downloaded photos to device
- Isle/0350/1 shows image 9115
- Unlinked image 9115
- Downloaded photos to device
- Isle/0350/1 shows a blank image (as previous screenshot) - expected a message. Sync status screen show 0 sync problems on photos.
- Deleted all photos
- Downloaded photos to device
- Isle/0350/1 shows a blank image
