### ISSUE TITLE
Add a panel to show the sync status for photos and on home screen

### ISSUE THREAD

**Issue by LaineS** [exeGesIS-SDM/CAMS-Mobile#95]

**Comment by am-esdm** [comment]
The 'Sync Status' panel will have the same format as the existing entity panel entries, i.e. 'Total' photos synced (downloaded), 'Last Sync' date and time and 'Sync Problems' total number of problems.

The new message on the app home screen will take the same approach as the existing main survey data sync messages (but will not merge with or replace it, it will be a separate additional message), i.e. stating the last successful 'download photos' sync date and time, plus stating clearly to the user if there were any problems with the last photos sync and instructing them to sync photos again if this was the case.

**Comment by LaineS** [comment]
v4.4.4

Panel added to the sync status screen. No panel added to the home screen.

**Comment by am-esdm** [comment]
**Device:** Samsung Galaxy Tab A
**OS Version:** Android v5.1.1
**App Version:** v4.4.4
**Sync Account:** xgWCP
**Status:** Partial pass - outstanding work required
**Details:**
Some elements of the specification completed: photo sync process completed without any obvious problems, the Sync Status window now has a 'Library Link Photos' panel, with 'Total:' ('12846' records in my case after the sync) and 'Last Sync:' entries ('14/07/2020 17:32' in my case after the sync). It is missing the 'Sync Problems' (total number of problems) entry from the specification. Also the app home screen message hasn't been implemented yet, but we knew that was going to be the case at this stage and @LaineS will be working on that later this week (Friday)

**Comment by LaineS** [comment]
* Add sync problems
* Add home screen info

**Comment by am-esdm** [comment]
**Device:** Samsung Galaxy Tab A
**OS Version:** Android v5.1.1
**App Version:** v4.4.5
**Sync Account:** xgEastSus
**Status:** Fail
**Details:**
The 'Library Link Photos' panel in the Sync Status window is showing, even though the 'G_SHOW_DOWNLOADBUTTON_FORLIBRARYLINK' config entry's value is 'false' - would expect this panel (or at least the sync button for photos) to be hidden if this config value is false, to allow for users who don't have the LibraryLink Web Service/this functionality enabled

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.5
**Sync Account**: xgStaffs
**Status**: Fail
**Details**: as above, this panel does NOT get hidden when `G_SHOW_DOWNLOADBUTTON_FORLIBRARYLINK = false;` - I think this settign should hide the whole panel

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.5
**Sync Account**: xgWCP
**Status**: Fail
**Details**: Noticed during testing that when clearing photos from the device, the count of photos does not always reset to 0

**Comment by LaineS** [comment]
Agreed to leave this at the moment (the issue is the delete process is still going on and the sync status screen refreshes, so if the delete process is slow the sync screen still shows some photos are in the DB. If you leave the screen and re-enter it, the delete process is usually finished by then and the screen shows no photos left)

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.5
**Sync Account**: xgEastSus
**Status**: Fail
**Details**: This does NOT get hidden when `G_SHOW_DOWNLOADBUTTON_FORLIBRARYLINK = false;` - this setting should hide the whole panel. Also observed the same on xgDev config

This is the xgEastSus config file: [CAMSMobileConfig_xgEastSus.js](https://github.com/exeGesIS-SDM/CAMS-Mobile/files/4987719/CAMSMobileConfig_xgEastSus.txt)

**Comment by LaineS** [comment]
Working  v4.4.6

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.6
**Sync Account**: xgEastSus / xgDev / xgWcp
**Status**: Pass
**Details**: Switched between config files, checked whether panel on sync status screen and button appear
- Synced xgEastSus config (turned off in config) - did not display
- Synced xgDev config (turned off in config) - did not display
- Synced xgWcp config (turned on in config) - displayed
- Synced xgDev config (turned off in config) - did not display

**Comment by am-esdm** [comment]
**Device:** Samsung Galaxy Tab A
**OS Version:** Android v5.1.1
**App Version:** 4.4.6
**Sync Account:** xgEastSus
**Status:** Pass
**Details:** Synced xgEastSus config, checked whether the 'Library Link Photos' panel (and its sync button) appeared, it didn't (as expected, as the 'G_SHOW_DOWNLOADBUTTON_FORLIBRARYLINK' config was set to false)
