### ISSUE TITLE
Furniture UDF values cleared from CAMS Mobile database when task assigned to child issue, or child issue edited from CAMS Desktop

### ISSUE THREAD

**Issue by am-esdm** [exeGesIS-SDM/CAMS-Mobile#97]
When a task assignment is added from cams desktop to an existing issue on an existing item of furniture that were already on CAMS Mobile, after syncing that new task assignment onto CAMS Mobile it clears the Furniture UDF data values for that furniture record from the CAMS Mobile database, therefore the UDF values display as blank on the Furniture record in CAMS Mobile and if any edits are made to that Furniture record in CAMS Mobile, when it is synced back to CAMS Desktop it syncs back 'updated' empty values for the Furniture UDF fields, overwriting (and therefore clearing) any existing UDF values in the main CAMS database for that Furniture record. Tested in CAMS Mobile v4.3.12 using the xgEastSus testing sync account - device was Samsung Galaxy Tab A, using Android OS v5.1.1

**Comment by am-esdm** [comment]
Tested this again using the xgWCP testing sync account (same app version, device and Android OS version) and the problem did not replicate on this sync account

**Comment by am-esdm** [comment]
Replicated this in v4.4.6 too (xgWCP testing sync account), had to assign a few tasks before the problem occurred

**Comment by am-esdm** [comment]
Carried out further testing on the live East Sussex CC CAMS system following a support request from the client. Found a possible expansion of this issue, in that the problem (loss of existing parent Furniture record's UDF values) appears to also occur when a new unresolved Issue record is added to the Furniture (from Desktop in the case of this initial testing), synced onto Mobile, and then the Issue record is resolved (also from Desktop during this initial testing) and that 'resolved' status is then synced onto CAMS Mobile. Replicated this process twice in a row with the same problem result (loss of parent Furniture record's UDF values in Mobile database). Need to test this on another setup now to confirm

**Comment by am-esdm** [comment]
> Carried out further testing on the live East Sussex CC CAMS system following a support request from the client. Found a possible expansion of this issue, in that the problem (loss of existing parent Furniture record's UDF values) appears to also occur when a new unresolved Issue record is added to the Furniture (from Desktop in the case of this initial testing), synced onto Mobile, and then the Issue record is resolved (also from Desktop during this initial testing) and that 'resolved' status is then synced onto CAMS Mobile. Replicated this process twice in a row with the same problem result (loss of parent Furniture record's UDF values in Mobile database). Need to test this on another setup now to confirm

Confirmed this via the same scenario tested on xgWCP testing account, same result

**Comment by am-esdm** [comment]
Carried out further testing via the xgWCP test sync account, using CAMS Mobile v4.3.12. Found that the edit to the child issue record causing the problem as described above can be more varied than just changing the issue status, e.g. in CAMS Desktop I appended some more text to an existing issue 'Problem' field entry for a child issue record that was already on CAMS Mobile and then saved it, then synced the updated issue record onto CAMS Mobile (it's the child of a Furniture record): this caused the same problem. Looks likely that any edit to the child Issue record will cause the problem. Changed title of task to reflect this

**Comment by am-esdm** [comment]
> Carried out further testing via the xgWCP test sync account, using CAMS Mobile v4.3.12. Found that the edit to the child issue record causing the problem as described above can be more varied than just changing the issue status, e.g. in CAMS Desktop I appended some more text to an existing issue 'Problem' field entry for a child issue record that was already on CAMS Mobile and then saved it, then synced the updated issue record onto CAMS Mobile (it's the child of a Furniture record): this caused the same problem. Looks likely that any edit to the child Issue record will cause the problem. Changed title of task to reflect this

Tested this again using the same process, except different field changed: changing the value of the issue 'Officer' field didn't cause the problem (tested it twice, no problem either time - but it could be intermittent perhaps and would occur on 3rd or 4th attempt maybe?), but then tried adding a new value into (a previously empty) 'Description' field and this caused the problem - I think overall we can assume most edits to the issue record appear to cause the problem

**Comment by LaineS** [comment]
Tested: 
- Using xgWCP, sync data and checked Infra Gwyne/1467 downloads ok (it does and it has UDF field info). This displays correctly in the app
- Change the Infra on the desktop and sync to mobile, the new data downloaded has blank values for the UDF. So I think there is a bug in the API

http://camsmobile/proxy.ashx?https://camsapidemo.esdm.co.uk/5.1/Reference/XGWCP/API/api/camsdata/EntitiesWithUserFields/2020-09-18%2012:14/vieWebInfra/1/500

(NB this would also cause the issues with task assignment as described above)

**Comment by am-esdm** [comment]
> Tested:
> 
> * Using xgWCP, sync data and checked Infra Gwyne/1467 downloads ok (it does and it has UDF field info). This displays correctly in the app
> * Change the Infra on the desktop and sync to mobile, the new data downloaded has blank values for the UDF. So I think there is a bug in the API
> 
> http://camsmobile/proxy.ashx?https://camsapidemo.esdm.co.uk/5.1/Reference/XGWCP/API/api/camsdata/EntitiesWithUserFields/2020-09-18%2012:14/vieWebInfra/1/500
> 
> (NB this would also cause the issues with task assignment as described above)

Note for clarity for all, the "Change the Infra on the desktop" bit here referred to adding a new Issue to the Furniture

**Comment by LaineS** [comment]
Update:
* There is a bug in one of the CAMS server views that meant the LastUpdatedDate column for the UDF table was not being updated when TD/Ali added an issue to the furniture item. This meant if the app syncs, it gets blank UDF's from the API and then if the mobile user edits the Furniture item the app re-uploads blank values
* The solution needed to to fix CAMS Desktop (or the CAMS vies) so the LastUpdatedField is updated. (TD has done this and tested ok initially, more testing needed using the current version of the mobile app - no mobile change needed)

**NB This bug can lead to data loss, if there are other actions a user can take in CAMS Desktop that do not correctly update the LastUpdatedDate field then the mobile app can upload null values which will overwrite the values in CAMS Desktop**

**Comment by Timothy-D** [comment]
**Test 1 - Add Issue**
1. UDFs added to Records Gwyne/727, Gwyne/728 & Gwyne/3279.
1. Synced to emulator
2. Waited around 10 minutes
3. Added issues to these items
4. Synced to emulator
5. Issues display against furniture items and UDFs still shown.

**Test 2 - Update Issue**
1. Updated Problem field of issues on Gwyne/728 & Gwyne/729
2. Synced to emulator
3. Issues showed updated OK, UDFs still appeared on furniture items
4. Added condition records & synced from emulator.
5. UDF data is retained

**Test 3 - Assign Issue**
1. Issue on Gwyne/727 assigned to a user
2. Synced to emulator
3. Issue showed OK, UDFs still appeared on furniture item
4. Added condition records & synced from emulator.
5. UDF data is retained
6. Issue on Gwyne/729 assigned to the user logged in on the mobile app
7.Synced to emulator
8. Issue showed OK with task highlight, UDFs still appeared on furniture items.
4. Added condition records & synced from emulator.
5. UDF data is retained

This requires the update to vieWebInfraUserFields - pushed to CamsDocs GIT repo

**Comment by am-esdm** [comment]
After vieWebInfraUserFields update had been applied, tested on xgWCP and xgStaffs sync accounts as follows:

**xgWCP:**

**Test 1 - Add Issue**

1. Used Furniture record Gwyne/724 that already had UDF values
2. Added an issue to the furniture on CAMS Desktop
3. Synced to CAMS Mobile
4. Issue displayed against furniture item and UDFs values still shown on the furniture

**Test 2 - Update Issue**

1. Updated Problem field of issue on Gwyne/724 (Furniture record with UDF values), on CAMS Desktop
2. Synced to CAMS Mobile
3. Issue showed update OK, UDF values still appeared on furniture item

**Test 3 - Assign Issue**

1. Issue on Gwyne/724 assigned to the user logged in on CAMS Mobile
2. Synced to CAMS Mobile
3. Issue showed OK on furniture, with task highlight, UDF values still appeared on furniture item

**xgStaffs:**

**Test 1 - Add Issue**

1. Used Furniture record 092/4 that already had UDF values
2. Added an issue to the furniture on CAMS Desktop
3. Synced to CAMS Mobile
4. Issue displayed against furniture item and UDFs values still shown on the furniture

**Test 2 - Update Issue**

1. Updated Problem field of issue on 092/4 (Furniture record with UDF values), on CAMS Desktop
2. Synced to CAMS Mobile
3. Issue showed update OK, UDF values still appeared on furniture item

**Test 3 - Assign Issue**

1. Issue on 092/4 assigned to the user logged in on CAMS Mobile
2. Synced to CAMS Mobile
3. Issue showed OK on furniture, with task highlight, UDF values still appeared on furniture item

All looks ok

**Comment by am-esdm** [comment]
Also tested as follows on CAMS Mobile v4.4.7 (tab A device, Android v5.1.1):

**xgWCP test sync account:**

**Test 1 - Add Issue**

1. Used Furniture record Gwyne/718 that already had UDF values
2. Added an issue to the furniture on CAMS Desktop
3. Synced to CAMS Mobile
4. Issue displayed against furniture item and UDFs values still shown on the furniture

**Test 2 - Update Issue**

1. Updated Problem field of issue on Gwyne/718 (Furniture record with UDF values), on CAMS Desktop
2. Synced to CAMS Mobile
3. Issue showed update OK, UDF values still appeared on furniture item

**Test 3 - Assign Issue**

1. Issue on Gwyne/718 assigned to the user logged in on CAMS Mobile
2. Synced to CAMS Mobile
3. Issue showed OK on furniture, with task highlight, UDF values still appeared on furniture item

All ok
