### ISSUE TITLE
v4.x.x - Please ensure default API url and LLWS photos url are both xgDemo or xgDev

### ISSUE THREAD

**Issue by am-esdm** [exeGesIS-SDM/CAMS-Mobile#98]

**Comment by LaineS** [comment]
No changes mad to these URL's and they are the same as the previous version (which is correct I think)

**Comment by LaineS** [comment]
Now changed to
`G_LIBRARYLINK_GetFileInfoByXGTypeAndXGKey_URL = "https://camsapidemo.esdm.co.uk/5.1/Reference/XGDemo/LLWS/LibraryLinkWS.asmx/GetFileInfoByXGTypeAndXGKeyWithURLS";`

**Comment by am-esdm** [comment]
For v4.4.10: Seems ok so far

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 3
**OS Version**: Android 11
**App Version**: 4.5.3
**Status**: OK
